function f = comp_iufwt2(ca, ch, cv, cd, g, a, J, scaling)
%COMP_IUFWT Compute Inverse Undecimated DWT
%   Usage:  f = comp_iufwt2(ca, cv, g, a, J, scaling);
%
%   Input parameters:
%         ca     : L*W array of approximation coefficients.
%         ch     : L*W*M array of horizontal coefficients, M = J*(filtNo - 1).
%         cv     : L*W*M array of vertical coefficients, M = J*(filtNo - 1).
%         cd     : L*W*M array of diagonal coefficients, M = J*(filtNo - 1).
%         g     : Synthesis wavelet filters-Cell-array of length *filtNo*.
%         J     : Number of filterbank iterations.
%         a     : Upsampling factors - array of length *filtNo*.
%
%   Output parameters:
%         f     : Reconstructed data - L*W array.
%
%

    % see comp_fwt2 for explanantion
    assert( ...
        a(1) == a(2), ...
        sprintf( ...
            '%s %s', ...
            'First two elements of a are not equal.', ...
            'Such wavelet filterbank is not suported.' ...
            ) ...
        );

    % For holding the impulse responses.
    filtNo = length(g);
    gOffset = cellfun(@(gEl) gEl.offset, g(:));

    % Optionally scale the filters
    g = comp_filterbankscale(g(:), a(:), scaling);

    %Change format to a matrix
    gMat = cell2mat(cellfun(@(gEl) gEl.h(:), g(:)', 'UniformOutput', 0));

    c = ca;
    jj = J;
    M = J*(filtNo - 1);
    runPtr = M - (filtNo - 2);
    while(1 <= jj)
        % Current iteration filter upsampling factor.
        filtUps = a(1)^(jj - 1);

        % Zero index position of the upsampled filetrs.
        offset = filtUps.*gOffset ;%+ filtUps;

        % Reconstruct vertical coefficients
        cvr = zeros(size(cv, 1), filtNo - 1, size(cv, 2));
        dd = 0;
        while(filtNo - 2 >= dd)
            % Reshape coefficients
            cr = zeros(size(cd, 2), filtNo - 1, size(cd, 1));
            ii = 0;
            while(filtNo - 2 >= ii)
                cr(:, ii + 1, :) = reshape( ...
                    cd(:, :, runPtr + ii), ...
                    size(cd, 1), ...
                    size(cd, 2) ...
                    )';

                ++ii;

            endwhile;

            % Run the filterbank
            cvr(:, dd + 1, :) = comp_iatrousfilterbank_td( ...
                [ ...
                    reshape( ...
                        cv(:, :, runPtr + dd)', ...
                        size(cv, 2), ...
                        1, ...
                        size(cv, 1) ...
                        ), ...
                    cr ...
                    ], ...
                gMat, ...
                filtUps, ...
                offset ...
                )';

            ++dd;

        endwhile;

        % Reconstruct vertical approximation coefficients
        cr = zeros(size(ch, 2), filtNo - 1, size(ch, 1));
        ii = 0;
        while(filtNo - 2 >= ii)
            cr(:, ii + 1, :) = reshape( ...
                ch(:, :, runPtr + ii)', ...
                size(ch, 2), ...
                1, ...
                size(ch, 1) ...
                );
            ++ii;

        endwhile;

        % Run the filterbank
        c = comp_iatrousfilterbank_td( ...
            [ ...
                reshape(c', size(c, 2), 1, size(c, 1)), ...
                cr ...
                ], ...
            gMat, ...
            filtUps, ...
            offset ...
            )';

        % Reconstruct vertical approximation coefficients. Run the filterbank
        c = comp_iatrousfilterbank_td( ...
            [ ...
                reshape(c, size(c, 1), 1, size(c, 2)), ...
                cvr ...
                ], ...
            gMat, ...
            filtUps, ...
            offset ...
            );

        % Bookkeeping
        runPtr = runPtr - (filtNo - 1);

        --jj;

     endwhile;

     % Copy to the output.
     f = c;

endfunction;
