item_list_dlg_version = '1.0';

source('./gui_commons.m');
source('./app_uistyle_model.m');
source('./item_list_model.m');
source('./item_list_view.m');
source('./control_panel_view.m');

% -----------------------------------------------------------------------------
%
% Function 'itemListDlgNewDlg':
%
% Use:
%       -- itemListDlgNewDlg(item_list)
%       -- itemListDlgNewDlg(..., "PROPERTY", VALUE, ...)
%       -- hdlg = itemListDlgNewDlg(...)
%
% Description:
%          TODO: Add function description here
%
% -----------------------------------------------------------------------------
function hdlg = itemListDlgNewDlg(varargin)

    % Store function name into variable
    % for easier management of error messages ---------------------------------
    fname = 'itemListDlgNewDlg';
    use_case_a = strjoin({ ...
        ' -- ', ...
        fname, ...
        '(item)' ...
        }, '');
    use_case_b = strjoin({ ...
        ' -- ', ...
        fname, ...
        '(..., "PROPERTY", VALUE, ...)' ...
        }, '');
    use_case_c = strjoin({ ...
        ' -- hview = ', ...
        fname, ...
        '(...)' ...
        }, '');

    % Define number of supported positional parameters ------------------------

    % Define number of supported positional (numerical) parameters
    numpos = 1;

    % Define number of supported optional parameters
    numopt = 5;

    % Validate input arguments ------------------------------------------------

    % Validate number of input arguments. We determin the minimum number of
    % input arguments as number of suported positional arguments (numpos). The
    % number of maximal possible input arguments we determine as sum of numpos
    % and number of optional parameters multiplied by two (this takes into
    % account values of supplied optional parameters)
    narginchk(numpos, numpos + 2*numopt);

    % Parse arguments
    [ ...
        pos, ...
        dlg_tag, ...
        title, ...
        uistyle, ...
        hparent, ...
        on_dlg_result_callback ...
        ] = parseparams( ...
        varargin, ...
        'dlg_tag', 'item_edit_dlg', ...
        'title', 'Item List View', ...
        'uistyle', appUiStyleModelNewUiStyle(), ...  % Use default UI style
        'parent', NaN, ...  %WARNING: do not set this to 0 it is the result of groot()!
        'OnDlgResultCallback', NaN ...
        );

    % Validate the number of positional parameters
    if(numpos ~= numel(pos))
        error( ...
            'Invalid call to %s. Correct usage is:\n%s\n%s\n%s', ...
            fname, ...
            use_case_a, ...
            use_case_b, ...
            use_case_c ...
            );

    endif;

    % Validate argument values ------------------------------------------------

    % Validate item argument
    item_list = pos{1};
    if(~itemListModelIsItemListObj(item_list))
        error( ...
            '%s: item_list must be an instance of the Item List Model data structure', ...
            fname
            );

    endif;

    % Validate dlg_tag argument
    if(~ischar(dlg_tag))
        error( ...
            '%s: dlg_tag must be a character array', ...
            fname
            );
    endif;

    % Validate title argument
    if(~ischar(title))
        error( ...
            '%s: title must be a character array', ...
            fname
            );
    endif;

    % Validate uistyle argument
    if(~appUiStyleModelIsUiStyleObj(uistyle))
        error( ...
            '%s: uistyle must be an instance of the App UI Style data structure', ...
            fname
            );

    endif;

    % Validate hparent argument
    if(~isfigure(hparent) && ~isnan(hparent))
        error( ...
            '%s: hparent must be handle to a figure or NaN', ...
            fname
            );

    endif;

    % Validate item_modified_callback argument
    if( ...
            ~is_function_handle(on_dlg_result_callback) ...
            && ~isnan(on_dlg_result_callback) ...
            )
        error( ...
            '%s: on_dlg_result_callback must be handle to a function or NaN', ...
            fname
            );

    endif;

    % Create dialog figure ----------------------------------------------------

    % Check if we have parent object
    if(isnan(hparent))
        % We don't have handle to a parent UI container, so we need to run 'Item
        % List View' as a standalone application, within it's own figure and
        % with underlying app_data

        % Initialize GUI toolkit
        graphics_toolkit qt;

        % Create figure and define it as parent to the 'Item List' view
        hdlg = figure( ...
            'name', title, ...
            'menubar', 'none', ...
            'tag', dlg_tag ...
            );

    else
        % We have a handle to the parent figure
        hdlg = figure( ...
            'parent', hparent, ...
            'name', title, ...
            'menubar', 'none', ...
            'tag', dlg_tag ...
            );

    endif;

    % Save item_list data -----------------------------------------------------
    fig_data = guidata(hdlg);
    fig_data.item_list = item_list;
    guidata(hdlg, fig_data);

    % Save required app data
    app_data = guidata(hparent);
    app_data = setfield( ...
        app_data, ...
        strjoin({view_tag, 'data'}, '_'), ...
        itemListSelectionModelNewSelection(item_list) ...
        );
    guidata(hparent, app_data);

    % Create dialog view ------------------------------------------------------
    itemListDlgLayoutView( ...
        hdlg, ...
        item_list, ...
        'dlg_tag', dlg_tag, ...
        'title', 'Items', ...
        'uistyle', uistyle, ...
        'OnBtnPushCallback', NaN ...
        % 'OnBtnPushCallback', itemListDlgGenerateOnBtnPushCallback( ...
        %     hdlg, ...
        %     dlg_tag, ...
        %     hparent, ...
        %     on_dlg_result_callback ...
        %     ) ...
        );

    % Connect signals ---------------------------------------------------------

    % Connect size changed signal to it's slot
    set( ...
        hdlg, ...
        'sizechangedfcn', {@itemListDlgUpdateView, dlg_tag, uistyle} ...
        );

endfunction;

% -----------------------------------------------------------------------------
%
% Function 'itemListDlgLayoutView':
%
% Use:
%       -- itemListDlgLayoutView(hparent)
%       -- itemListDlgLayoutView(..., "PROPERTY", VALUE, ...)
%       -- hview = itemListDlgLayoutView()
%
% Description:
%          TODO: Add function description here
%
% -----------------------------------------------------------------------------
function hview = itemListDlgLayoutView(varargin)

    % Store function name into variable
    % for easier management of error messages ---------------------------------
    fname = 'itemEditDlgLayoutView';
    use_case_a = strjoin({ ...
        ' -- hview = ', ...
        fname, ...
        '(hparent)' ...
        }, '');
    use_case_b = strjoin({ ...
        ' -- ', ...
        fname, ...
        '(..., "PROPERTY", VALUE, ...)' ...
        }, '');
    use_case_c = strjoin({ ...
        ' -- hview = ', ...
        fname, ...
        '(...)' ...
        }, '');

    % Define number of supported positional parameters ------------------------

    % Define number of supported positional (numerical) parameters
    numpos = 1;

    % Define number of supported optional parameters
    numopt = 4;

    % Validate input arguments ------------------------------------------------

    % Validate number of input arguments
    narginchk(numpos, numpos + 2*numopt);

    % Parse arguments
    [ ...
        pos, ...
        dlg_tag, ...
        title, ...
        uistyle, ...
        on_btn_push_callback ...
        ] = parseparams( ...
        varargin, ...
        'dlg_tag', 'item_list_dlg', ...
        'title', 'Manage Items', ...
        'uistyle', appUiStyleModelNewUiStyle(), ...  % Use default UI style
        'OnBtnPushCallback', NaN ...
        );

    % Validate the number of positional parameters
    if(numpos ~= numel(pos))
        error( ...
            'Invalid call to %s. Correct usage is:\n%s\n%s\n%s', ...
            fname, ...
            use_case_a, ...
            use_case_b, ...
            use_case_c ...
            );

    endif;

    % Validate hparent argument
    hparent = pos{1};
    if(~isfigure(hparent))
        error( ...
            '%s: hparent must be handle to a figure', ...
            fname
            );

    endif;

    % Validate dlg_tag argument
    if(~ischar(dlg_tag))
        error( ...
            '%s: dlg_tag must be a character array', ...
            fname
            );
    endif;

    % Validate title argument
    if(~ischar(title))
        error( ...
            '%s: title must be a character array', ...
            fname
            );
    endif;

    % Validate uistyle argument
    if(~appUiStyleModelIsUiStyleObj(uistyle))
        error( ...
            '%s: uistyle must be an instance of the App UI Style data structure', ...
            fname
            );

    endif;

    % Validate callback argument
    if( ...
            ~is_function_handle(on_btn_push_callback) ...
            && ~isnan(on_btn_push_callback) ...
            )
        error( ...
            '%s: on_btn_push_callback must be handle to a function or NaN', ...
            fname
            );

    endif;

    % Validate gui data
    fig_data = guidata(hparent);
    if(~isfield(fig_data, 'item_list'))
        error( ...
            '%s: given figure does not contain item_list data', ...
            fname
            );

    endif;

    % Create containers for the views -----------------------------------------
    data_cntr = uipanel( ...
        'parent', hparent, ...
        'bordertype', 'none', ...
        'position', [0.0, 0.2, 1.0, 0.8] ...
        );
    controls_cntr = uipanel( ...
        'parent', hparent, ...
        'bordertype', 'none', ...
        'position', [0.0, 0.0, 1.0, 0.2] ...
        );

    % Create views ------------------------------------------------------------
    hdataview = itemListViewNewView( ...
        fig_data.item_list, ...
        'view_tag', strjoin({dlg_tag, 'data_view'}, '_'), ...
        'title', title, ...
        'uistyle', uistyle, ...
        'parent', data_cntr, ...
        'ItemSelectionCallback', NaN, ...
        'ItemAddCallback', NaN, ...
        'ItemRemoveCallback', NaN ...
        );
    hcontrolsview = controlPanelViewNewView( ...
        'view_tag', strjoin({dlg_tag, 'controls_view'}, '_'), ...
        'title', '', ...
        'uistyle', uistyle, ...
        'parent', controls_cntr, ...
        'OnBtnPushCallback', on_btn_push_callback ...
        );

    hview = hdataview;

endfunction;

% -----------------------------------------------------------------------------
%
% Function 'itemListDlgUpdateView':
%
% Use:
%       -- itemListDlgUpdateView(hsrc, evt, dlg_tag, uistyle)
%
% Description:
%          TODO: Add function description here
%
% -----------------------------------------------------------------------------
function itemListDlgUpdateView(hsrc, evt, dlg_tag, uistyle)

    % Store function name into variable
    % for easier management of error messages ---------------------------------
    fname = 'itemListDlgUpdateView';
    use_case_a = strjoin({ ...
        ' -- ', ...
        fname, ...
        '(hsrc, evt, dlg_tag, uistyle)' ...
        }, '');

    % Validate input arguments ------------------------------------------------

    % Validate number of input arguments
    if(4 ~= nargin)
        error('Invalid call to %s. Correct usage is:\n%s', fname, use_case_a);

    endif;

    % Validate hsrc argument
    if(~isfigure(hsrc))
        error( ...
            '%s: hsrc must be handle to a figure', ...
            fname
            );

    endif;

    % We ignore evt argument

    % Validate dlg_tag argument
    if(~ischar(dlg_tag))
        error( ...
            '%s: dlg_tag must be a character array', ...
            fname
            );
    endif;

    % Validate uistyle argument
    if(~appUiStyleModelIsUiStyleObj(uistyle))
        error( ...
            '%s: uistyle must be an instance of the App UI Style data structure', ...
            fname
            );

    endif;

    % Construct view' tags ----------------------------------------------------
    dvtag = strjoin({dlg_tag, 'data_view'}, '_');
    cvtag = strjoin({dlg_tag, 'controls_view'}, '_');

    % Check if given tags exist in the figure handles table, and if they do call
    % the update functions for the each view
    hndls = guihandles(hsrc);
    if(isfield(hndls, dvtag) && isfield(hndls, cvtag))

        itemListViewUpdateView(hsrc, [], dvtag, uistyle);
        controlPanelViewUpdateView(hsrc, [], cvtag, uistyle);

    endif;

endfunction;

% -----------------------------------------------------------------------------
%
% Function 'itemListDlgOnItemSelectCallback':
%
% Use:
%       -- itemListDlgOnItemSelectCallback(hview, view_tag, idx)
%
% Description:
%          TODO: Add function description here
%
% -----------------------------------------------------------------------------
function itemListDlgOnItemSelectCallback(hview, view_tag, idx)

    % Store function name into variable
    % for easier management of error messages ---------------------------------
    fname = 'itemListDlgOnItemSelectCallback';
    use_case_a = strjoin({ ...
        ' -- ', ...
        fname, ...
        '(hview, view_tag, idx)' ...
        }, '');

    % Validate input arguments ------------------------------------------------

    % Validate number of input arguments
    if(2 ~= nargin)
        error('Invalid call to %s. Correct usage is:\n%s', fname, use_case_a);

    endif;

    % Validate hview argument
    if(~ishghandle(hview))
        error( ...
            '%s: hview must be handle to a graphics object', ...
            fname
            );

    endif;

    % Validate view_tag argument
    if(~ischar(view_tag))
        error( ...
            '%s: view_tag must be a character array', ...
            fname
            );
    endif;
    hfig = ancestor(hview, 'figure');
    if(~isfield(guihandles(hfig), view_tag))
        error( ...
            '%s: given view_tag does not belong to parent figure', ...
            fname
            );
    endif;

    % Validate idx argument
    validateattributes( ...
        idx, ...
        {'numeric'}, ...
        { ...
            '>=', 0, ...
            'finite', ...
            'integer', ...
            'nonempty', ...
            'nonnan', ...
            'scalar' ...
            }, ...
        fname, ...
        'idx' ...
        );

    % Change and save selected item index -------------------------------------

    % Get app data
    app_data = guidata(hfig);
    selection = getfield( ...
        app_data, ...
        strjoin({view_tag, 'data'}, '_') ...
        );

    selection.selected_item = idx;

    % Save changes
    app_data = setfield( ...
        app_data, ...
        strjoin({view_tag, 'data'}, '_'), ...
        selection ...
        );
    guidata(hview, app_data);

    % Nothing has changed in the view, so don't update it

endfunction;
