function result = buttonPanelViewController(varargin)

    [ ...
        pos, ...
        uistyle, ...
        hmaster, ...
        hview, ...
        hbtnaccept, ...
        hbtncncl, ...
        on_btn_push_callback, ...
        on_resize_callback ...
        ] = parseparams( ...
        varargin, ...
        'uistyle', appUiStyleModelNewUiStyle(), ...  % Use default UI style
        'hmaster', NaN, ...  %WARNING: do not set this to 0 it is the result of groot()!
        'hview', NaN, ...  %WARNING: do not set this to 0 it is the result of groot()!
        'hbtnaccept', NaN, ...  %WARNING: do not set this to 0 it is the result of groot()!
        'hbtncncl', NaN, ...  %WARNING: do not set this to 0 it is the result of groot()!
        'OnBtnPushCallback', NaN, ...
        'OnResizeCallback', NaN ...
        );

    function Controller(varargin)
        hsrc = varargin{1};
        evt = varargin{2};
        msg = varargin{3};

        if(isequal(hmaster, hsrc))
            if( ...
                    isequal('resize', msg) ...
                    && is_function_handle(on_resize_callback) ...
                    )
                on_resize_callback(uistyle, hview, hbtnaccept, hbtncncl);

            endif;

        elseif(isequal(hbtnaccept, hsrc))
            if( ...
                    isequal('clicked', msg) ...
                    && is_function_handle(on_btn_push_callback) ...
                    )
                on_btn_push_callback('accept');

            endif;

        elseif(isequal(hbtncncl, hsrc))
            if( ...
                    isequal('clicked', msg) ...
                    && is_function_handle(on_btn_push_callback) ...
                    )
                on_btn_push_callback('cancel');

            endif;

        endif;

    endfunction;

    result = @Controller;

endfunction;
