% 'gui_image_select_point' is a function from the package: 'GUI Elements RND'
%
%  -- gui_image_select_point(I)
%       Small GuI app that creates a new figure to show passed image

function gui_image_select_point(I)

    % Input validation section
    if(~isnumeric(I))
        error('Invalid data type!. Not defined for non-numerical data matrices.');

        return;

    elseif( ...
            1 == size(I, 1) ...
            || 1 == size(I, 2) ...
            || (1 ~= size(I, 3) && 3 ~= size(I, 3)) ...
            )
        error('Invalid data type!. Not a grayscale nor a RGB image.');

        return;

    endif;

    % Set GUI toolkit to Qt
    graphics_toolkit qt;

    % Spawn main figure
    main_figure = figure( ...
        'name', 'GUI Image Show', ...
        'sizechangedfcn', @update_main_figure ...
        % 'buttondownfcn', @image_click ...
        );

    % Get handle for the main figure
    h = guihandles(main_figure);
    h.main_figure = main_figure;

    % Define general padding value for GUI elements in pixels
    h.pix_pad = 6;

    % SPawn main panel
    h.main_panel = uipanel( ...
        'parent', main_figure, ...
        'bordertype', 'none' ...
        );

    % Get main panel draw area extents in pixels
    mps = getpixelposition(h.main_panel);

    % Calculate axes extents
    rel_hpad = h.pix_pad/(mps(3) - mps(1));
    rel_vpad = h.pix_pad/(mps(4) - mps(2));

    % Calculate postion for the left panel (image view) within main panel
    elpos = [ ...
        rel_hpad, ...
        rel_vpad, ...
        0.8 - 2*rel_hpad, ...
        1 - 2*rel_vpad ...
        ];

    % Set left panel
    h.left_panel = uipanel( ...
        'parent', h.main_panel, ...
        % 'title', 'Image', ...
        'position', elpos ...
        );

    % Calculate postion for the right panel (user controls) within main panel
    elpos = [ ...
        0.8 + rel_hpad, ...
        rel_vpad, ...
        0.2 - 2*rel_hpad, ...
        1 - 2*rel_vpad ...
        ];

    % Set right panel
    h.right_panel = uipanel( ...
        'parent', h.main_panel, ...
        'title', 'User Controls', ...
        'position', elpos ...
        );

    % Initialize axes for image display
    h.image_view = axes( ...
        'parent', h.left_panel, ...
        'position', [0 0 1 1] ...
        );
    %imshow(I, 'parent', image_view);
    himage = image(I, 'parent', h.image_view);
    axis(h.image_view, 'off');

    % Specify the callback function
    set(himage, 'ButtonDownFcn', @(s, e)image_click(h.image_view, I))

    % Set right panel controls
    h.pix_btn_height = 20;
    rel_btn_height = h.pix_btn_height/(mps(4) - mps(2));

    % SPawn undo button
    % elpos = [ ...
    %     rel_hpad, ...
    %     1 - 2*rel_vpad - rel_btn_height, ...
    %     1 - 2*rel_hpad, ...
    %     rel_btn_height ...
    %     ];
    elpos = [ ...
        rel_hpad, ...
        rel_vpad, ...
        1 - 2*rel_hpad, ...
        1 - 2*rel_vpad ...
        ];

    h.undo_btn = uicontrol( ...
        'parent', h.right_panel, ...
        'style', 'pushbutton', ...
        'string', 'Undo', ...
        'callback', @undo_push, ...
        'units', 'normalized', ...
        'position', elpos ...
        );


    % Save data and GUI handles
    guidata(main_figure, h);

endfunction;


function update_main_figure(hsrc, evt)
    if(hsrc == gcbf())
        h = guidata(hsrc);
        switch(gcbo())
            case {h.main_figure}

                % Get main panel draw area extents in pixels
                mps = getpixelposition(h.main_panel);

                % Calculate left and right panel extents
                rel_hpad = h.pix_pad/(mps(3) - mps(1));
                rel_vpad = h.pix_pad/(mps(4) - mps(2));

                % Calculate and set new position for the left panel
                elpos = [ ...
                    rel_hpad, ...
                    rel_vpad, ...
                    0.8 - 2*rel_hpad, ...
                    1 - 2*rel_vpad ...
                    ];
                set(h.left_panel, 'position', elpos);

                % Calculate and set new position for the right panel
                elpos = [ ...
                    0.8 + rel_hpad, ...
                    rel_vpad, ...
                    0.2 - 2*rel_hpad, ...
                    1 - 2*rel_vpad ...
                    ];
                set(h.right_panel, 'position', elpos);

        endswitch;

    endif;

endfunction;


function image_click(hax, img)

    % Get the location of the current mouse click
    current_point = get(hax, 'CurrentPoint');
    current_point = round(current_point(1,1:2));

    % Retrieve the pixel value at this point
    if(1 == size(img, 3))
        % We have a monochrome image
        data = img(sub2ind( ...
            size(img), ...
            current_point(2), ...
            current_point(1) ...
            ));

        % Print the data to the command window.
        printf( ...
            'x: %0.2f, y: %0.2f, pixel: %0.2f\n', ...
            current_point(1), ...
            current_point(2), ...
            data ...
            );

    else
        % We are dealing with an RGB image
        R = img(sub2ind( ...
            size(img), ...
            current_point(2), ...
            current_point(1), ...
            1 ...
            ));
        G = img(sub2ind( ...
            size(img), ...
            current_point(2), ...
            current_point(1), ...
            2 ...
            ));
        B = img(sub2ind( ...
            size(img), ...
            current_point(2), ...
            current_point(1), ...
            3 ...
            ));

        % Print the data to the command window.
        printf( ...
            'x: %0.2f, y: %0.2f, pixel: (%0.2f, %0.2f, %0.2f)\n', ...
            current_point(1), ...
            current_point(2), ...
            R, G, B ...
            );

    endif;

endfunction;


function undo_push(hsrc, evt)
endfunction;
