app_uistyle_model_version = '1.0';

% -----------------------------------------------------------------------------
%
% Function 'appUiStyleModelNewUiStyle':
%
% Use:
%       -- style = appUiStyleModelNewUiStyle(pad, cwd, rhg, bwd, bhg)
%
% Description:
%
% TODO: Add function description here
% -----------------------------------------------------------------------------
function style = appUiStyleModelNewUiStyle(pad=6, cwd=128, rhg=24, bwd=128, bhg=32)

    % Store function name into variable
    % for easier management of error messages ---------------------------------
    fname = 'appUiStyleModelNewUiStyle';
    use_case = ' -- style = appUiStyleModelNewUiStyle(pad, cwd, rhg, bwd, bhg)';

    % Validate input arguments ------------------------------------------------

    % Validate number of input arguments
    if(5 < nargin)
        error( ...
            'Invalid call to %s.  Correct usage is:\n%s\n%s\n%s', ...
            fname, ...
            use_case ...
            );

    endif;

    % Validate arguments
    validateattributes( ...
        pad, ...
        {'float'}, ...
        {'scalar', '>=', 1}, ...
        fname, ...
        'pad' ...
        );
    validateattributes( ...
        cwd, ...
        {'float'}, ...
        {'scalar', '>=', 1}, ...
        fname, ...
        'cwd' ...
        );
    validateattributes( ...
        rhg, ...
        {'float'}, ...
        {'scalar', '>=', 1}, ...
        fname, ...
        'rhg' ...
        );
    validateattributes( ...
        bwd, ...
        {'float'}, ...
        {'scalar', '>=', 1}, ...
        fname, ...
        'bwd' ...
        );
    validateattributes( ...
        bhg, ...
        {'float'}, ...
        {'scalar', '>=', 1}, ...
        fname, ...
        'bhg' ...
        );

    style = struct();
    style.padding_px = pad;
    style.column_width_px = cwd;
    style.row_height_px = rhg;
    style.btn_width_px = bwd;
    style.btn_height_px = bhg;

endfunction;

% -----------------------------------------------------------------------------
%
% Function 'appUiStyleModelIsUiStyleObj':
%
% Use:
%       -- result = appUiStyleModelIsUiStyleObj(obj)
%
% Description:
%
% TODO: Add function description here
% -----------------------------------------------------------------------------
function result = appUiStyleModelIsUiStyleObj(obj)

    % Store function name into variable
    % for easier management of error messages ---------------------------------
    fname = 'appUiStyleModelIsUiStyleObj';
    use_case = ' -- result = appUiStyleModelIsUiStyleObj(obj)';

    % Validate input arguments ------------------------------------------------

    % Validate number of input arguments
    if(1 ~= nargin)
        error( ...
            'Invalid call to %s. Correct usage is:\n%s', ...
            fname, ...
            use_case ...
            );

    endif;

    % Initialize return value to default
    result = false;

    if( ...
            isstruct(obj) ...
            && isfield(obj, 'padding_px') ...
            && isscalar(obj.padding_px) ...
            && isfloat(obj.padding_px) ...
            && (0 < obj.padding_px) ...
            && isfield(obj, 'column_width_px') ...
            && isscalar(obj.column_width_px) ...
            && isfloat(obj.column_width_px) ...
            && (0 < obj.column_width_px) ...
            && isfield(obj, 'row_height_px') ...
            && isscalar(obj.row_height_px) ...
            && isfloat(obj.row_height_px) ...
            && (0 < obj.row_height_px) ...
            && isfield(obj, 'btn_width_px') ...
            && isscalar(obj.btn_width_px) ...
            && isfloat(obj.btn_width_px) ...
            && (0 < obj.btn_width_px) ...
            && isfield(obj, 'btn_height_px') ...
            && isscalar(obj.btn_height_px) ...
            && isfloat(obj.btn_height_px) ...
            && (0 < obj.btn_height_px) ...
            )

        result = true;

    endif;

endfunction;
