% 'rctGUIAnalyzeFilm' is an application from the package: 'Radiochromi Film Toolbox'
%
%  -- rctGUIAnalyzeFilm()

% TODO: Remove following line when release is complete
pkg_name = 'Radiochromic Toolbox'

% =============================================================================
%
% Main Script Body Section
%
% =============================================================================

% -----------------------------------------------------------------------------
%
% Function 'rct_gui_analyze_film'
%
% -----------------------------------------------------------------------------
% TODO: Rename script's name and function's name to
% 'rct_gui_analyze_raw_film_v1' when release is complete
function rcGuiAnalyzeRawFilm()

    % Initialize GUI toolkit
    graphics_toolkit qt;

    % Initialize structure for keeping app data
    app = createAppDataset();
    app = newApp(app, 'scannerdb.csv', 'filmdb.csv');
    app = buildGUI(app);
    guidata(gcf(), app);

    % Update display
    refresh(gcf());

    % Wait for user to close the figure and then continue
    uiwait(app.gui.main_figure);

endfunction;




% =============================================================================
%
% Data Handling and Manipulation Routines Section
%
% =============================================================================

% -----------------------------------------------------------------------------
%
% Application Data Structure Routines
%
% -----------------------------------------------------------------------------
function app = newApp(scannerdb, filmdb)

    % Store function name into variable for easier management of error messages
    fname = 'newApp';

    % Validate input arguments
    if(2 ~= nargin)
        error( ...
            strjoin({ ...
                '%s: Invalid call to function.', ...
                'Expected 2 arguments in function call, got %d.' ...
                }), ...
            fname, ...
            nargin ...
            );

    endif;

    if(~ischar(scannerdb))
        error( ...
            strjoin({ ...
                '%s: Invalid data type for function parameter \"scannerdb\".', ...
                'Expected \"char\", got \"%s\".' ...
                }), ...
            fname, ...
            class(scannerdb) ...
            );

    endif;

    if(~ischar(filmdb))
        error( ...
            strjoin({ ...
                '%s: Invalid data type for function parameter \"filmdb\".', ...
                'Expected \"char\", got \"%s\".' ...
                }), ...
            fname, ...
            class(filmdb) ...
            );

    endif;

    app = struct();
    app.scannerdb = scannerdb;
    app.filmdb = filmdb;
    app.measurement = NaN;
    app.gui = NaN;

endfunction;

function result = isAppDataStruct(app)
    result = false;
    if( ...
            isstruct(app) ...
            && isfield(app, 'scannerdb') ...
            && ischar(app.scannerdb) ...
            && isfield(app, 'filmdb') ...
            && ischar(app.filmdb) ...
            && isfield(app, 'measurement') ...
            && isfield(app, 'gui') ...
            )
        result = true;

    endif;

endfunction;

% -----------------------------------------------------------------------------
%
% Measurement Data Structure Routines
%
% -----------------------------------------------------------------------------
function measurement = newMeasurement(title=NaN, date=NaN)

    % Store function name into variable for easier management of error messages
    fname = 'newMeasurement';

    % Validate input arguments
    if(~isnan(title) && ~ischar(title))
        error( ...
            strjoin({ ...
                '%s: Invalid data type for function parameter \"title\".', ...
                'Expected \"NaN\" or \"char\", got \"%s\".' ...
                }), ...
            fname, ...
            class(title) ...
            );

    endif;

    if(~isnan(date) && ~ischar(date))
        error( ...
            strjoin({ ...
                '%s: Invalid data type for function parameter \"date\".', ...
                'Expected \"NaN\" or \"char\", got \"%s\".' ...
                }), ...
            fname, ...
            class(date) ...
            );

    endif;

    measurement = struct();
    if(~isnan(title))
        measurement.title = title;

    else
        measurement.title = 'New Measurement';

    endif;
    if(~isnan(date))
        measurement.date = date;

    else
        measurement.date = strftime('%d.%m.%Y', localtime(time()));

    endif;
    measurement.scanner_device       = NaN;
    measurement.film                 = NaN;
    measurement.field                = NaN;
    measurement.pixel_data_smoothing = NaN;
    measurement.irradiated           = NaN;
    measurement.background           = NaN;
    measurement.zero_light           = NaN;
    measurement.dead_pixels          = NaN;
    measurement.optical_density      = NaN;
    measurement.roi                  = {};

endfunction;

function result = isMeasurementDataStruct(msr)
    result = false;
    if( ...
            isstruct(msr) ...
            && isfield(msr, 'title') ...
            && ischar(msr.title) ...
            && isfield(msr, 'date') ...
            && ischar(msr.date) ...
            && isfield(msr, 'scanner_device') ...
            && isfield(msr, 'film') ...
            && isfield(msr, 'field') ...
            && isfield(msr, 'pixel_data_smoothing') ...
            && isfield(msr, 'irradiated') ...
            && isfield(msr, 'background') ...
            && isfield(msr, 'zero_light') ...
            && isfield(msr, 'dead_pixels') ...
            && isfield(msr, 'optical_density') ...
            && isfield(msr, 'roi') ...
            && iscell(msr.roi) ...
            )
        result = true;

    endif;

endfunction;

% -----------------------------------------------------------------------------
%
% Scanner Device Data Structure Routines
%
% -----------------------------------------------------------------------------
function device = newScannerDevice(scannerdb=NaN, item=1)

    % Store function name into variable for easier management of error messages
    fname = 'newScannerDevice';

    % Validate input arguments
    if(~isnan(scannerdb) && ~ischar(scannerdb))
        error( ...
            strjoin({ ...
                '%s: Invalid data type for function parameter \"scannerdb\".', ...
                'Expected \"NaN\" or \"char\", got \"%s\".' ...
                }), ...
            fname, ...
            class(scannerdb) ...
            );

    endif;

    if(~isscalar(item) && ~isfloat(item))
        error( ...
            strjoin({ ...
                '%s: Invalid data type for function parameter \"item\".', ...
                'Expected \"floating point scalar\", got \"%s\".' ...
                }), ...
            fname, ...
            class(item) ...
            );

    endif;

    % Load device list first
    device_list = loadScannerDatabase(scannerdb);

    % Validate if 'device_list' can be indexed with supplied item number 'item'
    if(~isindex(item + 1, size(device_list, 1)))
        error( ...
            '%s: Index (%d) out of bounds [1, %d].', ...
            fname, ...
            item, ...
            size(device_list, 1) - 1 ...
            );

    endif;

    % Create structure and assign data
    device                     = struct();
    device.manufacturer        = device_list{item + 1, 1};
    device.model               = device_list{item + 1, 2};
    device.serial_number       = device_list{item + 1, 3};
    device.native_resolution   = device_list{item + 1, 4};
    device.scanning_mode       = device_list{item + 1, 5};
    device.scanning_resolution = device_list{item + 1, 6};

endfunction;

function result = isScannerDeviceStruct(sd)
    result = false;
    if( ...
            isstruct(sd) ...
            && isfield(sd, 'manufacturer') ...
            && ischar(sd.manufacturer) ...
            && isfield(sd, 'model') ...
            && ischar(sd.model) ...
            && isfield(sd, 'serial_number') ...
            && ischar(sd.serial_number) ...
            && isfield(sd, 'native_resolution') ...
            && ischar(sd.native_resolution) ...
            && isfield(sd, 'scanning_mode') ...
            && ischar(sd.scanning_mode) ...
            && isfield(sd, 'scanning_resolution') ...
            && ischar(sd.scanning_resolution) ...
            )
        result = true;

    endif;

endfunction;

function device_list = loadScannerDatabase(dbfile=NaN)

    % Define common window and message strings
    fname = 'loadScannerDatabase';
    window_title = 'RCT Analyze Raw Film: Load Scanner Database';

    % Initialize to default values
    device_list = { ...
        'Manufacturer', ...
        'Model', ...
        'Serial Number', ...
        'Native Resolution', ...
        'Scanning Mode', ...
        'Scanning Resolution'; ...
        'unknown', ...
        'unknown', ...
        'unknown', ...
        'unknown', ...
        'unknown', ...
        'unknown' ...
        };

    if(~isnan(dbfile) && ~scannerDatabaseExists(dbfile))
        % Show error dialog
        msgbox( ...
            sprintf( ...
                strjoin({ ...
                    'Scanner database \"%s\" is missing.' ...
                    'Using default values ...' ...
                    }), ...
                dbfile ...
                ), ...
            window_title, ...
            'warn' ...
            );

        % also send message to the workspace
        fprintf( ...
            stderr(), ...
            strjoin({ ...
                '%s: Scanner database \"%s\" is missing.' ...
                'Using default values ...\n' ...
                }), ...
            fname, ...
            dbfile ...
            );

        return;

    endif;

    % if(~scannerDatabaseIntegrityOk(path_to_file))
    %     errordlg( ...
    %         'Scanner database integrity check failed. Using default values ...', ...
    %         'RCT Analyze Raw Film: Missing Database' ...
    %         );
    %
    %     % Unload loaded packages
    %     pkg unload io;
    %
    %     return;
    %
    % endif;

    if(~isnan(dbfile))
        % Load required packages
        pkg load io;  % Required by 'csv2cell'

        % Load all known scanners
        device_list = csv2cell(dbfile);

        % Unload loaded packages
        pkg unload io;

    endif;

endfunction;

function result = scannerDatabaseExists(dbfile=NaN)

    % Store function name into variable for easier management of error messages
    fname = 'scannerDatabaseExists';

    % Validate input arguments
    if(~isnan(dbfile) && ~ischar(dbfile))
        error( ...
            strjoin({ ...
                '%s: Invalid data type for function parameter \"dbfile\".', ...
                'Expected \"NaN\" or \"char\", got \"%s\".' ...
                }), ...
            fname, ...
            class(dbfile) ...
            );

    endif;

    result = isfile(dbfile);

endfunction;

function result = scannerDatabaseIntegrityOk(path_to_file=NaN)
    % TODO: Add function implementation here

endfunction;

% -----------------------------------------------------------------------------
%
% Film Data Structure Routines
%
% -----------------------------------------------------------------------------
function film = newFilm(filmdb=NaN, item=1)

    % Store function name into variable for easier management of error messages
    fname = 'newFilm';

    % Validate input arguments
    if(~isnan(filmdb) && ~ischar(filmdb))
        error( ...
            strjoin({ ...
                '%s: Invalid data type for function parameter \"filmdb\".', ...
                'Expected \"NaN\" or \"char\", got \"%s\".' ...
                }), ...
            fname, ...
            class(filmdb) ...
            );

    endif;

    if(~isscalar(item) && ~isfloat(item))
        error( ...
            strjoin({ ...
                '%s: Invalid data type for function parameter \"item\".', ...
                'Expected \"floating point scalar\", got \"%s\".' ...
                }), ...
            fname, ...
            class(item) ...
            );

    endif;

    % Load film list
    film_list = loadFilmDatabase(filmdb);

    % Validate if 'film_list' can be indexed with supplied item number 'item'
    if(~isindex(item + 1, size(film_list, 1)))
        error( ...
            '%s: Index (%d) out of bounds [1, %d].', ...
            fname, ...
            item, ...
            size(film_list, 1) - 1 ...
            );

    endif;

    film              = struct();
    film.manufacturer = film_list{item + 1, 1};
    film.model        = film_list{item + 1, 2};
    film.custom_cut   = film_list{item + 1, 3};

endfunction;

function result = isFilmStruct(film)
    result = false;
    if( ...
            isstruct(film) ...
            && isfield(film, 'manufacturer') ...
            && ischar(film.manufacturer) ...
            && isfield(film, 'model') ...
            && ischar(film.model) ...
            && isfield(film, 'custom_cut') ...
            && ischar(film.custom_cut) ...
            )
        result = true;

    endif;

endfunction;

function film_list = loadFilmDatabase(dbfile=NaN)

    % Define common window and message strings
    fname = 'loadFilmDatabase';
    window_title = 'RCT Analyze Raw Film: Load Film Database';

    % Initialize to default values
    film_list = { ...
        'Manufacturer', ...
        'Model', ...
        'Custom Cut'; ...
        'unknown', ...
        'unknown', ...
        'unknown' ...
        };

    if(~isnan(dbfile) && ~filmDatabaseExists(dbfile))
        % Show error dialog
        msgbox( ...
            sprintf( ...
                strjoin({ ...
                    'Film database \"%s\" is missing.' ...
                    'Using default values ...' ...
                    }), ...
                dbfile ...
                ), ...
            window_title, ...
            'warn' ...
            );

        % also send message to the workspace
        fprintf( ...
            stderr(), ...
            strjoin({ ...
                '%s: Film database \"%s\" is missing.' ...
                'Using default values ...\n' ...
                }), ...
            fname, ...
            dbfile ...
            );

        return;

    endif;

    % if(~filmDatabaseIntegrityOk(path_to_file))
    %     errordlg( ...
    %         'Film database integrity check failed. Using default values ...', ...
    %         'RCT Analyze Raw Film: Missing Database' ...
    %         );
    %
    %     % Unload loaded packages
    %     pkg unload io;
    %
    %     return;
    %
    % endif;

    if(~isnan(dbfile))
        % Load required packages
        pkg load io;  % Required by 'csv2cell'

        % Load all known scanners
        film_list = csv2cell(dbfile);

        % Unload loaded packages
        pkg unload io;

    endif;

endfunction;

function result = filmDatabaseExists(dbfile=NaN)

    % Store function name into variable for easier management of error messages
    fname = 'filmDatabaseExists';

    % Validate input arguments
    if(~isnan(dbfile) && ~ischar(dbfile))
        error( ...
            strjoin({ ...
                '%s: Invalid data type for function parameter \"dbfile\".', ...
                'Expected \"NaN\" or \"char\", got \"%s\".' ...
                }), ...
            fname, ...
            class(dbfile) ...
            );

    endif;

    result = isfile(dbfile);

endfunction;

function result = filmDatabaseIntegrityOk(path_to_file)
    % TODO: Add function implementation here

endfunction;

% -----------------------------------------------------------------------------
%
% Field Data Structure Routines
%
% -----------------------------------------------------------------------------
function field = newField( ...
        beam_type='unknown', ...
        beam_energy='unknown', ...
        field_shape='unknown', ...
        field_size='unknown' ...
        )

    % Store function name into variable for easier management of error messages
    fname = 'newField';

    % Validate input arguments
    if(~ischar(beam_type))
        error( ...
            strjoin({ ...
                '%s: Invalid data type for function parameter \"beam_type\".', ...
                'Expected \"char\", got \"%s\".' ...
                }), ...
            fname, ...
            class(beam_type) ...
            );

    endif;

    if(~ischar(beam_energy))
        error( ...
            strjoin({ ...
                '%s: Invalid data type for function parameter \"beam_energy\".', ...
                'Expected \"char\", got \"%s\".' ...
                }), ...
            fname, ...
            class(beam_energy) ...
            );

    endif;

    if(~ischar(field_shape))
        error( ...
            strjoin({ ...
                '%s: Invalid data type for function parameter \"field_shape\".', ...
                'Expected \"char\", got \"%s\".' ...
                }), ...
            fname, ...
            class(field_shape) ...
            );

    endif;
    validatestring( ...
        field_shape, ...
        {'unknown', 'circular', 'rectangular', 'square', 'irregular'}, ...
        fname, ...
        'field_shape' ...
        );

    if(~ischar(field_size))
        error( ...
            strjoin({ ...
                '%s: Invalid data type for function parameter \"field_size\".', ...
                'Expected \"char\", got \"%s\".' ...
                }), ...
            fname, ...
            class(field_size) ...
            );

    endif;

    field             = struct();
    field.beam_type   = beam_type;
    field.beam_energy = beam_energy;
    field.field_shape = field_shape;
    field.field_size  = field_size;

endfunction;

function result = isFieldStruct(field)
    result = false;
    if( ...
            isstruct(field) ...
            && isfield(field, 'beam_type') ...
            && ischar(field.beam_type) ...
            && isfield(field, 'beam_energy') ...
            && ischar(field.beam_energy) ...
            && isfield(field, 'field_shape') ...
            && ischar(field.field_shape) ...
            && isfield(field, 'field_size') ...
            && ischar(field.field_size) ...
            )
        result = true;

    endif;

endfunction;

% -----------------------------------------------------------------------------
%
% Pixel Data Smoothing Structure Routines
%
% -----------------------------------------------------------------------------
function smoothing = newPixelDataSmoothing(method='none', window=[])

    % Store function name into variable for easier management of error messages
    fname = 'newPixelDataSmoothing';

    % Validate input arguments
    if(~ischar(method))
        error( ...
            strjoin({ ...
                '%s: Invalid data type for function parameter \"method\".', ...
                'Expected \"char\", got \"%s\".' ...
                }), ...
            fname, ...
            class(method) ...
            );

    endif;
    validatestring( ...
        method, ...
        {'none', 'median', 'wiener'}, ...
        fname, ...
        'method' ...
        );

    if(~isequal('none', method))
        validateattributes( ...
            window, ...
            {'numeric'}, ...
            { ...
                'vector', ...
                'numel', 2, ...
                'integer', ...
                '>=', 1 ...
                }, ...
            fname, ...
            'window' ...
            );

    endif;

    smoothing        = struct();
    smoothing.method = method;
    smoothing.window = window;

endfunction;

function result = isPixelDataSmoothingStruct(smt)
    result = false;
    if( ...
            isstruct(smt) ...
            && isfield(smt, 'method') ...
            && ischar(smt.method) ...
            && isfield(smt, 'window') ...
            && ismatrix(smt.window) ...
            )
        result = true;

    endif;

endfunction;

% -----------------------------------------------------------------------------
%
% Irradiated Data Structure Routines
%
% -----------------------------------------------------------------------------
function irradiated = newIrradiatedDataset(msr, irrdt, scdt, varargin)

    % Define common window and message strings
    fname = 'newIrradiatedDataset';
    window_title = 'RCT Analyze Raw Film: New Irradiated Dataset';
    progress_tracker_title = 'New Irradiated Dataset';

    % Validate input arguments
    if(~isMeasurementDataStruct(msr))
        error('%s: Invalid data or measurement not set.', fname);

    endif;

    if(~isPixelDataSmoothingStruct(msr.pixel_data_smoothing))
        error('%s: Invalid data or pixel data smoothing not set.', fname);

    endif;

    if(~ischar(irrdt))
        error( ...
            strjoin({ ...
                '%s: Invalid data type for function parameter \"irrdt\".', ...
                'Expected \"char\", got \"%s\".' ...
                }), ...
            fname, ...
            class(irrdt) ...
            );

    endif;

    if(~ischar(scdt))
        error( ...
            strjoin({ ...
                '%s: Invalid data type for function parameter \"scdt\".', ...
                'Expected \"char\", got \"%s\".' ...
                }), ...
            fname, ...
            class(scdt) ...
            );

    endif;

    % Initialize data structures for keeping computation results
    irradiated = NaN;
    pwmean     = [];
    pwstd      = [];

    % Initialize loop counter
    idx = 1;

    % Display information on the loading process progress
    progress_tracker = waitbar( ...
        0.0, ...
        'Loading scanset ...', ...
        'name', progress_tracker_title ...
        );

    % Validate input files , check dimensions integrity of the given images,
    % calculate mean pixel value, pxelwise standard deviation, and pixelwise
    % stdev RMS
    while(nargin - 3 >= idx)
        img = [];

        % Validate input arguments
        if(~ischar(varargin{idx}))
            % Kill image reading progress tracker
            if(ishandle(progress_tracker))
                delete(progress_tracker);

            endif;

            % Display error and abort execution
            error( ...
                strjoin({ ...
                    '%s: Invalid data type for varargin{%d}.', ...
                    'Expected \"char\", got \"%s\".' ...
                    }), ...
                fname, ...
                idx, ...
                class(varargin{idx}) ...
                );

        endif;

        try
            img = imread(varargin{idx});

        catch err
            % Kill image reading progress tracker
            if(ishandle(progress_tracker))
                delete(progress_tracker);

            endif;

            % Format error message string for display to screen
            errmsg = strrep(err.message, '\', '\\');  % Escape backslashes

            % Show error dialog
            msgbox( ...
                { ...
                    sprintf('Error loading input scan: %d. Check log for details', idx), ...
                    'Aborting loading operation ...' ...
                    }, ...
                window_title, ...
                'error' ...
                );

            % also send message to the workspace
            fprintf( ...
                stderr(), ...
                '%s: %s. Aborting loading operation ...\n', ...
                fname, ...
                err.message ...
                );

            % Abort loading the scanset
            return;

        end_try_catch;

        % Check if we are dealing with an 48 bit image
        if(~isequal('uint16', class(img)))
            % Kill image reading progress tracker
            if(ishandle(progress_tracker))
                delete(progress_tracker);

            endif;

            % Format error message string for display to screen
            errmsg = sprintf( ...
                'Not an 48 bit image (%s).', ...
                strrep(varargin{idx}, '\', '\\') ...  % Escape backslashes
                );

            % Show error dialog
            msgbox( ...
                { ...
                    strrep(errmsg, '_', '\_'), ...  % Escape underscores
                    'Aborting loading operation ...' ...
                    }, ...
                window_title, ...
                'error' ...
                );

            % also send message to the workspace
            fprintf( ...
                stderr(), ...
                sprintf( ...
                    '%s: %s Aborting loading operation ...\n', ...
                    fname, ...
                    errmsg ...
                    ) ...
                );

            % Abort loading the scanset
            return;

        endif;

        % Load required package
        pkg load image;  % Required for 'isrgb'

        % Check if we have an RGB image
        if(~isrgb(img))
            % Kill image reading progress tracker
            if(ishandle(progress_tracker))
                delete(progress_tracker);

            endif;

            % Format error message string for display to screen
            errmsg = sprintf( ...
                'Not an RGB image (%s).', ...
                strrep(varargin{idx}, '\', '\\') ...  % Escape backslashes
                );

            % Image does not have three color channels
            msgbox( ...
                { ...
                    strrep(errmsg, '_', '\_'), ...  % Escape underscores
                    'Aborting loading operation ...' ...
                    }, ...
                window_title, ...
                'error' ...
                );

            % also send message to the workspace
            fprintf( ...
                stderr(), ...
                sprintf( ...
                    '%s: %s Aborting loading operation ...\n', ...
                    fname, ...
                    errmsg ...
                    ) ...
                );

            % Unload loaded package
            pkg unload image;

            % Abort loading the scanset
            return;

        endif;

        % Unload loaded packages
        pkg unload image;

        % Check if all given images have the same size
        if(1 == idx)
            % If this is the first image read, allocate space for the
            % mean pixel values and pixelwise standard deviation
            pwstd = pwmean = zeros(size(img));

        elseif(~isequal(size(img), size(pwmean)))
            % Kill image reading progress tracker
            if(ishandle(progress_tracker))
                delete(progress_tracker);

            endif;

            % Format error message string for display to screen
            errmsg = sprintf( ...
                'Image size does not conform to the size of other images (%s).', ...
                strrep(varargin{idx}, '\', '\\') ...  % Escape backslashes
                );

            % Image size does not conform to the size of other images
            msgbox( ...
                { ...
                    strrep(errmsg, '_', '\_'), ...  % Escape underscores
                    'Aborting loading operation ...' ...
                    }, ...
                window_title, ...
                'error' ...
                );

            % also send message to the workspace
            fprintf( ...
                stderr(), ...
                sprintf( ...
                    '%s: %s Aborting loading operation ...\n', ...
                    fname, ...
                    errmsg ...
                    ) ...
                );

            % Clean up GUI
            if(ishandle(progress_tracker))
                delete(progress_tracker);

            endif;

            % Abort loading the scanset
            return;

        endif;

        % Smooth out pixel data if required
        smoothed = zeros(size(img));
        if(isequal('median', msr.pixel_data_smoothing.method))
            % Load required package
            pkg load image;

            % Smooth data using median filter
            smoothed(:, :, 1) = medfilt2( ...
                img(:, :, 1), ...
                msr.pixel_data_smoothing.window ...
                );
            smoothed(:, :, 2) = medfilt2( ...
                img(:, :, 2), ...
                msr.pixel_data_smoothing.window ...
                );
            smoothed(:, :, 3) = medfilt2( ...
                img(:, :, 3), ...
                msr.pixel_data_smoothing.window ...
                );

            % Unload loaded package
            pkg unload image;

        elseif(isequal('wiener', msr.pixel_data_smoothing.method))
            % Load required package
            pkg load image;

            % Smooth data using wiener filter
            smoothed(:, :, 1) = wiener2( ...
                img(:, :, 1), ...
                msr.pixel_data_smoothing.window ...
                );
            smoothed(:, :, 2) = wiener2( ...
                img(:, :, 2), ...
                msr.pixel_data_smoothing.window ...
                );
            smoothed(:, :, 3) = wiener2( ...
                img(:, :, 3), ...
                msr.pixel_data_smoothing.window ...
                );

            % Unload loaded package
            pkg unload image;

        else
            smoothed = img;

        endif;

        % Accumulate mean pixel value
        pwmean = pwmean + (double(smoothed) ./ (nargin - 3));

        waitbar(idx/(nargin - 3), progress_tracker);

        idx = idx + 1;

    endwhile;

    % Kill image reading progress tracker
    if(ishandle(progress_tracker))
        delete(progress_tracker);

    endif;

    % Reset counter
    idx = 1;

    % Display progress information on calculation of standard deviation
    progress_tracker = waitbar( ...
        0.0, ...
        'Calculating standard deviation ...', ...
        'name', progress_tracker_title ...
        );

    % Calculate sum of squared differences from mean pixel value
    while(nargin - 3 >= idx)
        % Read image again
        img = imread(varargin{idx});

        % Smooth out pixel data again if required
        smoothed = zeros(size(img));
        if(isequal('median', msr.pixel_data_smoothing.method))
            % Load required package
            pkg load image;

            % Smooth data using median filter
            smoothed(:, :, 1) = medfilt2( ...
                img(:, :, 1), ...
                msr.pixel_data_smoothing.window ...
                );
            smoothed(:, :, 2) = medfilt2( ...
                img(:, :, 2), ...
                msr.pixel_data_smoothing.window ...
                );
            smoothed(:, :, 3) = medfilt2( ...
                img(:, :, 3), ...
                msr.pixel_data_smoothing.window ...
                );

            % Unload loaded package
            pkg unload image;

        elseif(isequal('wiener', msr.pixel_data_smoothing.method))
            % Load required package
            pkg load image;

            % Smooth data using wiener filter
            smoothed(:, :, 1) = wiener2( ...
                img(:, :, 1), ...
                msr.pixel_data_smoothing.window ...
                );
            smoothed(:, :, 2) = wiener2( ...
                img(:, :, 2), ...
                msr.pixel_data_smoothing.window ...
                );
            smoothed(:, :, 3) = wiener2( ...
                img(:, :, 3), ...
                msr.pixel_data_smoothing.window ...
                );

            % Unload loaded package
            pkg unload image;

        else
            smoothed = img;

        endif;

        % Accumulate the sum of squared differences
        pwstd = pwstd + (double(smoothed) - pwmean).^2;

        % Update progress tracker
        waitbar(idx/(nargin - 3), progress_tracker);

        idx = idx + 1;

    endwhile;

    % Kill stdev progress tracker
    if(ishandle(progress_tracker))
        delete(progress_tracker);

    endif;

    % Only divide by N - 1 if we are dealing with more than one image (scan)
    if(1 < nargin - 3)
        pwstd = pwstd ./ ((nargin - 3) - 1);

    endif;
    pwstd = pwstd.^0.5;

    % Calculate overall standard deviation as RMS of pixelwise standard
    % deviation
    standard_deviation = rms(pwstd);

    % Fill the return structure with calculated data
    irradiated                    = struct();
    irradiated.irradiation_date   = irrdt;
    irradiated.scan_date          = scdt;
    irradiated.file_list          = varargin;
    irradiated.pixel_data         = pwmean;
    irradiated.standard_deviation = standard_deviation;

endfunction;

function result = isIrradiatedDataStruct(irr)
    result = false;
    if( ...
            isstruct(irr) ...
            && isfield(irr, 'irradiation_date') ...
            && isfield(irr, 'scan_date') ...
            && isfield(irr, 'file_list') ...
            && isfield(irr, 'pixel_data') ...
            && isfield(irr, 'standard_deviation') ...
            && ischar(irr.irradiation_date) ...
            && ischar(irr.scan_date) ...
            && iscell(irr.file_list) ...
            && ~isempty(irr.pixel_data) ...
            && (3 == size(irr.pixel_data, 3)) ...
            && ismatrix(irr.pixel_data(:, :, 1)) ...
            && ismatrix(irr.pixel_data(:, :, 2)) ...
            && ismatrix(irr.pixel_data(:, :, 3)) ...
            && isvector(irr.standard_deviation) ...
            && (3 == size(irr.standard_deviation, 1)) ...
            && isfloat(irr.standard_deviation) ...
            )
        result = true;

    endif;

endfunction;

% -----------------------------------------------------------------------------
%
% Background Data Structure Routines
%
% -----------------------------------------------------------------------------
function background = newBackgroundDataset(msr, scdt, varargin)

    % Define common window and message strings
    fname = 'newBackgroundDataset';
    window_title = 'RCT Analyze Raw Film: New Background Dataset';
    progress_tracker_title = 'New Background Dataset';

    % Validate input arguments
    if(~isMeasurementDataStruct(msr))
        error('%s: Invalid data or measurement not set.', fname);

    endif;

    if(~isIrradiatedDataStruct(msr.irradiated))
        error('%s: Invalid data or irradiated data set not set.', fname);

    endif;

    if(~ischar(scdt))
        error( ...
            strjoin({ ...
                '%s: Invalid data type for function parameter \"scdt\".', ...
                'Expected \"char\", got \"%s\".' ...
                }), ...
            fname, ...
            class(scdt) ...
            );

    endif;

    % Initialize return value to default
    background = NaN;

    % Check for number of scans in the reference dataset
    if(numel(msr.irradiated.file_list) ~= nargin - 2)
        % Number of images in the dataset does not match number of images in the
        % reference dataset. Display error mesages and abort loading
        msgbox( ...
            { ...
                'Number of images in the dataset', ...
                'does not match number of images', ...
                'in the reference (irradiated) dataset.', ...
                'Aborting loading operation ...' ...
                }, ...
            window_title, ...
            'error' ...
            );

        % also send message to the workspace
        fprintf( ...
            stderr(), ...
            strjoin( ...
                { ...
                    '%s: Number of images in the dataset does not match ', ...
                    'number of images in the reference (irradiated) ', ...
                    'dataset. Aborting loading operation ...\n' ...
                    } ...
                ), ...
            fname ...
            );

        % Abort loading the scanset
        return;

    endif;

    % Display information on the loading process progress
    progress_tracker = waitbar( ...
        0.0, ...
        'Loading scanset ...', ...
        'name', progress_tracker_title ...
        );

    % Initialize data structures for keeping computation results
    pwmean     = [];
    pwstd      = [];

    % Initialize loop counter
    idx = 1;

    % Validate input files , check dimensions integrity of the given images,
    % calculate mean pixel value, pxelwise standard deviation, and pixelwise
    % stdev RMS
    while(nargin - 2 >= idx)
        img = [];

        % Validate input arguments
        if(~ischar(varargin{idx}))
            % Kill image reading progress tracker
            if(ishandle(progress_tracker))
                delete(progress_tracker);

            endif;

            % Display error and abort execution
            error( ...
                strjoin({ ...
                    '%s: Invalid data type for varargin{%d}.', ...
                    'Expected \"char\", got \"%s\".' ...
                    }), ...
                fname, ...
                idx, ...
                class(varargin{idx}) ...
                );

        endif;

        try
            img = imread(varargin{idx});

        catch err
            % Kill image reading progress tracker
            if(ishandle(progress_tracker))
                delete(progress_tracker);

            endif;

            % Format error message string for display to screen
            errmsg = strrep(err.message, '\', '\\');  % Escape backslashes

            % Show error dialog
            msgbox( ...
                { ...
                    sprintf('Error loading input scan: %d. Check log for details', idx), ...
                    'Aborting loading operation ...' ...
                    }, ...
                window_title, ...
                'error' ...
                );

            % also send message to the workspace
            fprintf( ...
                stderr(), ...
                '%s: %s. Aborting loading operation ...\n', ...
                fname, ...
                err.message ...
                );

            % Abort loading the scanset
            return;

        end_try_catch;

        % Check if we are dealing with an 48 bit image
        if(~isequal('uint16', class(img)))
            % Kill image reading progress tracker
            if(ishandle(progress_tracker))
                delete(progress_tracker);

            endif;

            % Format error message string for display to screen
            errmsg = sprintf( ...
                'Not an 48 bit image (%s).', ...
                strrep(varargin{idx}, '\', '\\') ...  % Escape backslashes
                );

            % Show error dialog
            msgbox( ...
                { ...
                    strrep(errmsg, '_', '\_'), ...  % Escape underscores
                    'Aborting loading operation ...' ...
                    }, ...
                window_title, ...
                'error' ...
                );

            % also send message to the workspace
            fprintf( ...
                stderr(), ...
                sprintf( ...
                    '%s: %s Aborting loading operation ...\n', ...
                    fname, ...
                    errmsg ...
                    ) ...
                );

            % Abort loading the scanset
            return;

        endif;

        % Load required packages
        pkg load image;  % Required for 'isrgb'

        % Check if we have an RGB image
        if(~isrgb(img))
            % Kill image reading progress tracker
            if(ishandle(progress_tracker))
                delete(progress_tracker);

            endif;

            % Format error message string for display to screen
            errmsg = sprintf( ...
                'Not an RGB image (%s).', ...
                strrep(varargin{idx}, '\', '\\') ...  % Escape backslashes
                );

            % Image does not have three color channels
            msgbox( ...
                { ...
                    strrep(errmsg, '_', '\_'), ...  % Escape underscores
                    'Aborting loading operation ...' ...
                    }, ...
                window_title, ...
                'error' ...
                );

            % also send message to the workspace
            fprintf( ...
                stderr(), ...
                sprintf( ...
                    '%s: %s Aborting loading operation ...\n', ...
                    fname, ...
                    errmsg ...
                    ) ...
                );

            % Unload loaded packages
            pkg unload image;

            % Abort loading the scanset
            return;

        endif;

        % Unload loaded packages
        pkg unload image;

        % Check if all given images have the same size as refernce dataset
        if(~isequal(size(img), size(msr.irradiated.pixel_data)))
            % Kill image reading progress tracker
            if(ishandle(progress_tracker))
                delete(progress_tracker);

            endif;

            % Format error message string for display to screen
            errmsg = sprintf( ...
                'Image size does not conform to the size of the reference image (%s).', ...
                strrep(varargin{idx}, '\', '\\') ...  % Escape backslashes
                );

            % Image size does not conform to the size of other images
            msgbox( ...
                { ...
                    strrep(errmsg, '_', '\_'), ...  % Escape underscores
                    'Aborting loading operation ...' ...
                    }, ...
                window_title, ...
                'error' ...
                );

            % also send message to the workspace
            fprintf( ...
                stderr(), ...
                sprintf( ...
                    '%s: %s Aborting loading operation ...\n', ...
                    fname, ...
                    errmsg ...
                    ) ...
                );

            % Clean up GUI
            if(ishandle(progress_tracker))
                delete(progress_tracker);

            endif;

            % Abort loading the scanset
            return;

        endif;

        if(1 == idx)
            % If this is the first image read, allocate space for the
            % mean pixel values and pixelwise standard deviation
            pwstd = pwmean = zeros(size(img));

        endif;

        % Smooth out pixel data if required
        smoothed = zeros(size(img));
        if(isequal('median', msr.pixel_data_smoothing.method))
            % Load required package
            pkg load image;

            % Smooth data using median filter
            smoothed(:, :, 1) = medfilt2( ...
                img(:, :, 1), ...
                msr.pixel_data_smoothing.window ...
                );
            smoothed(:, :, 2) = medfilt2( ...
                img(:, :, 2), ...
                msr.pixel_data_smoothing.window ...
                );
            smoothed(:, :, 3) = medfilt2( ...
                img(:, :, 3), ...
                msr.pixel_data_smoothing.window ...
                );

            % Unload loaded package
            pkg unload image;

        elseif(isequal('wiener', msr.pixel_data_smoothing.method))
            % Load required package
            pkg load image;

            % Smooth data using wiener filter
            smoothed(:, :, 1) = wiener2( ...
                img(:, :, 1), ...
                msr.pixel_data_smoothing.window ...
                );
            smoothed(:, :, 2) = wiener2( ...
                img(:, :, 2), ...
                msr.pixel_data_smoothing.window ...
                );
            smoothed(:, :, 3) = wiener2( ...
                img(:, :, 3), ...
                msr.pixel_data_smoothing.window ...
                );

            % Unload loaded package
            pkg unload image;

        else
            smoothed = img;

        endif;

        % Accumulate mean pixel value
        pwmean = pwmean + (double(smoothed) ./ (nargin - 2));

        waitbar(idx/(nargin - 2), progress_tracker);

        idx = idx + 1;

    endwhile;

    % Kill image reading progress tracker
    if(ishandle(progress_tracker))
        delete(progress_tracker);

    endif;

    % Reset counter
    idx = 1;

    % Display progress information on calculation of standard deviation
    progress_tracker = waitbar( ...
        0.0, ...
        'Calculating standard deviation ...', ...
        'name', progress_tracker_title ...
        );

    % Calculate sum of squared differences from mean pixel value
    while(nargin - 2 >= idx)
        % Read image again
        img = imread(varargin{idx});

        % Smooth out pixel data again if required
        smoothed = zeros(size(img));
        if(isequal('median', msr.pixel_data_smoothing.method))
            % Load required package
            pkg load image;

            % Smooth data using median filter
            smoothed(:, :, 1) = medfilt2( ...
                img(:, :, 1), ...
                msr.pixel_data_smoothing.window ...
                );
            smoothed(:, :, 2) = medfilt2( ...
                img(:, :, 2), ...
                msr.pixel_data_smoothing.window ...
                );
            smoothed(:, :, 3) = medfilt2( ...
                img(:, :, 3), ...
                msr.pixel_data_smoothing.window ...
                );

            % Unload loaded package
            pkg unload image;

        elseif(isequal('wiener', msr.pixel_data_smoothing.method))
            % Load required package
            pkg load image;

            % Smooth data using wiener filter
            smoothed(:, :, 1) = wiener2( ...
                img(:, :, 1), ...
                msr.pixel_data_smoothing.window ...
                );
            smoothed(:, :, 2) = wiener2( ...
                img(:, :, 2), ...
                msr.pixel_data_smoothing.window ...
                );
            smoothed(:, :, 3) = wiener2( ...
                img(:, :, 3), ...
                msr.pixel_data_smoothing.window ...
                );

            % Unload loaded package
            pkg unload image;

        else
            smoothed = img;

        endif;

        % Accumulate the sum of squared differences
        pwstd = pwstd + (double(smoothed) - pwmean).^2;

        % Update progress tracker
        waitbar(idx/(nargin - 2), progress_tracker);

        idx = idx + 1;

    endwhile;

    % Kill stdev progress tracker
    if(ishandle(progress_tracker))
        delete(progress_tracker);

    endif;

    % Only divide by N - 1 if we are dealing with more than one image (scan)
    if(1 < nargin - 2)
        pwstd = pwstd ./ ((nargin - 2) - 1);

    endif;
    pwstd = pwstd.^0.5;

    % Calculate overall standard deviation as RMS of pixelwise standard
    % deviation
    standard_deviation = rms(pwstd);

    % Fill the return structure with calculated data
    background                    = struct();
    background.scan_date          = scdt;
    background.file_list          = varargin;
    background.pixel_data         = pwmean;
    background.standard_deviation = standard_deviation;

endfunction;

function result = isBackgroundDataStruct(bkg)
    result = false;
    if( ...
            isstruct(bkg) ...
            && isfield(bkg, 'scan_date') ...
            && isfield(bkg, 'file_list') ...
            && isfield(bkg, 'pixel_data') ...
            && isfield(bkg, 'standard_deviation') ...
            && ischar(bkg.scan_date) ...
            && iscell(bkg.file_list) ...
            && ~isempty(bkg.pixel_data) ...
            && (3 == size(bkg.pixel_data, 3)) ...
            && ismatrix(bkg.pixel_data(:, :, 1)) ...
            && ismatrix(bkg.pixel_data(:, :, 2)) ...
            && ismatrix(bkg.pixel_data(:, :, 3)) ...
            && isvector(bkg.standard_deviation) ...
            && (3 == size(bkg.standard_deviation, 1)) ...
            && isfloat(bkg.standard_deviation) ...
            )
        result = true;

    endif;

endfunction;

% -----------------------------------------------------------------------------
%
% Zero Light Data Structure Routines
%
% -----------------------------------------------------------------------------
function zero_light = newZeroLightDataset(msr, scdt, varargin)

    % Define common window and message strings
    fname = 'newZeroLightDataset';
    window_title = 'RCT Analyze Raw Film: New Zero-Light Dataset';
    progress_tracker_title = 'New Zero-Light Dataset';

    % Validate input arguments
    if(~isMeasurementDataStruct(msr))
        error('%s: Invalid data or measurement not set.', fname);

    endif;

    if(~isIrradiatedDataStruct(msr.irradiated))
        error('%s: Invalid data or irradiated data set not set.', fname);

    endif;

    if(~ischar(scdt))
        error( ...
            strjoin({ ...
                '%s: Invalid data type for function parameter \"scdt\".', ...
                'Expected \"char\", got \"%s\".' ...
                }), ...
            fname, ...
            class(scdt) ...
            );

    endif;

    % Initialize return value to default
    zero_light = NaN;

    % Check for number of scans in the reference dataset
    if(numel(msr.irradiated.file_list) ~= nargin - 2)
        % Number of images in the dataset does not match number of images in the
        % reference dataset. Display error mesages and abort loading
        msgbox( ...
            { ...
                'Number of images in the dataset', ...
                'does not match number of images', ...
                'in the reference (irradiated) dataset.', ...
                'Aborting loading operation ...' ...
                }, ...
            window_title, ...
            'error' ...
            );

        % also send message to the workspace
        fprintf( ...
            stderr(), ...
            strjoin( ...
                { ...
                    '%s: Number of images in the dataset does not match ', ...
                    'number of images in the reference (irradiated) ', ...
                    'dataset. Aborting loading operation ...\n' ...
                    } ...
                ), ...
            fname ...
            );

        % Abort loading the scanset
        return;

    endif;

    % Display information on the loading process progress
    progress_tracker = waitbar( ...
        0.0, ...
        'Loading scanset ...', ...
        'name', progress_tracker_title ...
        );

    % Initialize data structures for keeping computation results
    pwmean = [];
    pwstd  = [];

    % Initialize loop counter
    idx = 1;

    % Validate input files , check dimensions integrity of the given images,
    % calculate mean pixel value, pxelwise standard deviation, and pixelwise
    % stdev RMS
    while(nargin - 2 >= idx)
        img = [];

        % Validate input arguments
        if(~ischar(varargin{idx}))
            % Kill image reading progress tracker
            if(ishandle(progress_tracker))
                delete(progress_tracker);

            endif;

            % Display error and abort execution
            error( ...
                strjoin({ ...
                    '%s: Invalid data type for varargin{%d}.', ...
                    'Expected \"char\", got \"%s\".' ...
                    }), ...
                fname, ...
                idx, ...
                class(varargin{idx}) ...
                );

        endif;

        try
            img = imread(varargin{idx});

        catch err
            % Kill image reading progress tracker
            if(ishandle(progress_tracker))
                delete(progress_tracker);

            endif;

            % Format error message string for display to screen
            errmsg = strrep(err.message, '\', '\\');  % Escape backslashes

            % Show error dialog
            msgbox( ...
                { ...
                    sprintf('Error loading input scan: %d. Check log for details', idx), ...
                    'Aborting loading operation ...' ...
                    }, ...
                window_title, ...
                'error' ...
                );

            % also send message to the workspace
            fprintf( ...
                stderr(), ...
                '%s: %s. Aborting loading operation ...\n', ...
                fname, ...
                err.message ...
                );

            % Abort loading the scanset
            return;

        end_try_catch;

        % Check if we are dealing with an 48 bit image
        if(~isequal('uint16', class(img)))
            % Kill image reading progress tracker
            if(ishandle(progress_tracker))
                delete(progress_tracker);

            endif;

            % Format error message string for display to screen
            errmsg = sprintf( ...
                'Not an 48 bit image (%s).', ...
                strrep(varargin{idx}, '\', '\\') ...  % Escape backslashes
                );

            % Show error dialog
            msgbox( ...
                { ...
                    strrep(errmsg, '_', '\_'), ...  % Escape underscores
                    'Aborting loading operation ...' ...
                    }, ...
                window_title, ...
                'error' ...
                );

            % also send message to the workspace
            fprintf( ...
                stderr(), ...
                sprintf( ...
                    '%s: %s Aborting loading operation ...\n', ...
                    fname, ...
                    errmsg ...
                    ) ...
                );

            % Abort loading the scanset
            return;

        endif;

        % Load required packages
        pkg load image;  % Required for 'isrgb'

        % Check if we have an RGB image
        if(~isrgb(img))
            % Kill image reading progress tracker
            if(ishandle(progress_tracker))
                delete(progress_tracker);

            endif;

            % Format error message string for display to screen
            errmsg = sprintf( ...
                'Not an RGB image (%s).', ...
                strrep(varargin{idx}, '\', '\\') ...  % Escape backslashes
                );

            % Image does not have three color channels
            msgbox( ...
                { ...
                    strrep(errmsg, '_', '\_'), ...  % Escape underscores
                    'Aborting loading operation ...' ...
                    }, ...
                window_title, ...
                'error' ...
                );

            % also send message to the workspace
            fprintf( ...
                stderr(), ...
                sprintf( ...
                    '%s: %s Aborting loading operation ...\n', ...
                    fname, ...
                    errmsg ...
                    ) ...
                );

            % Unload loaded packages
            pkg unload image;

            % Abort loading the scanset
            return;

        endif;

        % Unload loaded packages
        pkg unload image;

        % Check if all given images have the same size as the reference dataset
        if(~isequal(size(img), size(msr.irradiated.pixel_data)))
            % Kill image reading progress tracker
            if(ishandle(progress_tracker))
                delete(progress_tracker);

            endif;

            % Format error message string for display to screen
            errmsg = sprintf( ...
                'Image size does not conform to the size of the reference image (%s).', ...
                strrep(varargin{idx}, '\', '\\') ...  % Escape backslashes
                );

            % Image size does not conform to the size of other images
            msgbox( ...
                { ...
                    strrep(errmsg, '_', '\_'), ...  % Escape underscores
                    'Aborting loading operation ...' ...
                    }, ...
                window_title, ...
                'error' ...
                );

            % also send message to the workspace
            fprintf( ...
                stderr(), ...
                sprintf( ...
                    '%s: %s Aborting loading operation ...\n', ...
                    fname, ...
                    errmsg ...
                    ) ...
                );

            % Clean up GUI
            if(ishandle(progress_tracker))
                delete(progress_tracker);

            endif;

            % Abort loading the scanset
            return;

        endif;

        if(1 == idx)
            % If this is the first image read, allocate space for the
            % mean pixel values and pixelwise standard deviation
            pwstd = pwmean = zeros(size(img));

        endif;

        % Smooth out pixel data if required
        smoothed = zeros(size(img));
        if(isequal('median', msr.pixel_data_smoothing.method))
            % Load required package
            pkg load image;

            % Smooth data using median filter
            smoothed(:, :, 1) = medfilt2( ...
                img(:, :, 1), ...
                msr.pixel_data_smoothing.window ...
                );
            smoothed(:, :, 2) = medfilt2( ...
                img(:, :, 2), ...
                msr.pixel_data_smoothing.window ...
                );
            smoothed(:, :, 3) = medfilt2( ...
                img(:, :, 3), ...
                msr.pixel_data_smoothing.window ...
                );

            % Unload loaded package
            pkg unload image;

        elseif(isequal('wiener', msr.pixel_data_smoothing.method))
            % Load required package
            pkg load image;

            % Smooth data using wiener filter
            smoothed(:, :, 1) = wiener2( ...
                img(:, :, 1), ...
                msr.pixel_data_smoothing.window ...
                );
            smoothed(:, :, 2) = wiener2( ...
                img(:, :, 2), ...
                msr.pixel_data_smoothing.window ...
                );
            smoothed(:, :, 3) = wiener2( ...
                img(:, :, 3), ...
                msr.pixel_data_smoothing.window ...
                );

            % Unload loaded package
            pkg unload image;

        else
            smoothed = img;

        endif;

        % Accumulate mean pixel value
        pwmean = pwmean + (double(smoothed) ./ (nargin - 2));

        waitbar(idx/(nargin - 2), progress_tracker);

        idx = idx + 1;

    endwhile;

    % Kill image reading progress tracker
    if(ishandle(progress_tracker))
        delete(progress_tracker);

    endif;

    % Reset counter
    idx = 1;

    % Display progress information on calculation of standard deviation
    progress_tracker = waitbar( ...
        0.0, ...
        'Calculating standard deviation ...', ...
        'name', progress_tracker_title ...
        );

    % Calculate sum of squared differences from mean pixel value
    while(nargin - 2 >= idx)
        % Read image again
        img = imread(varargin{idx});

        % Smooth out pixel data again if required
        smoothed = zeros(size(img));
        if(isequal('median', msr.pixel_data_smoothing.method))
            % Load required package
            pkg load image;

            % Smooth data using median filter
            smoothed(:, :, 1) = medfilt2( ...
                img(:, :, 1), ...
                msr.pixel_data_smoothing.window ...
                );
            smoothed(:, :, 2) = medfilt2( ...
                img(:, :, 2), ...
                msr.pixel_data_smoothing.window ...
                );
            smoothed(:, :, 3) = medfilt2( ...
                img(:, :, 3), ...
                msr.pixel_data_smoothing.window ...
                );

            % Unload loaded package
            pkg unload image;

        elseif(isequal('wiener', msr.pixel_data_smoothing.method))
            % Load required package
            pkg load image;

            % Smooth data using wiener filter
            smoothed(:, :, 1) = wiener2( ...
                img(:, :, 1), ...
                msr.pixel_data_smoothing.window ...
                );
            smoothed(:, :, 2) = wiener2( ...
                img(:, :, 2), ...
                msr.pixel_data_smoothing.window ...
                );
            smoothed(:, :, 3) = wiener2( ...
                img(:, :, 3), ...
                msr.pixel_data_smoothing.window ...
                );

            % Unload loaded package
            pkg unload image;

        else
            smoothed = img;

        endif;

        % Accumulate the sum of squared differences
        pwstd = pwstd + (double(smoothed) - pwmean).^2;

        % Update progress tracker
        waitbar(idx/(nargin - 2), progress_tracker);

        idx = idx + 1;

    endwhile;

    % Kill stdev progress tracker
    if(ishandle(progress_tracker))
        delete(progress_tracker);

    endif;

    % Only divide by N - 1 if we are dealing with more than one image (scan)
    if(1 < nargin - 2)
        pwstd = pwstd ./ ((nargin - 2) - 1);

    endif;
    pwstd = pwstd.^0.5;

    % Calculate overall standard deviation as RMS of pixelwise standard
    % deviation
    standard_deviation = rms(pwstd);

    % Fill the return structure with calculated data
    zero_light                    = struct();
    zero_light.scan_date          = scdt;
    zero_light.file_list          = varargin;
    zero_light.pixel_data         = pwmean;
    zero_light.standard_deviation = standard_deviation;

endfunction;

function result = isZeroLightDataStruct(zrl)
    result = false;
    if( ...
            isstruct(zrl) ...
            && isfield(zrl, 'scan_date') ...
            && isfield(zrl, 'file_list') ...
            && isfield(zrl, 'pixel_data') ...
            && isfield(zrl, 'standard_deviation') ...
            && ischar(zrl.scan_date) ...
            && iscell(zrl.file_list) ...
            && ~isempty(zrl.pixel_data) ...
            && (3 == size(zrl.pixel_data, 3)) ...
            && ismatrix(zrl.pixel_data(:, :, 1)) ...
            && ismatrix(zrl.pixel_data(:, :, 2)) ...
            && ismatrix(zrl.pixel_data(:, :, 3)) ...
            && isvector(zrl.standard_deviation) ...
            && (3 == size(zrl.standard_deviation, 1)) ...
            && isfloat(zrl.standard_deviation) ...
            )
        result = true;

    endif;

endfunction;

% -----------------------------------------------------------------------------
%
% Dead Pixels Data Structure Routines
%
% -----------------------------------------------------------------------------

function dead_pixels_mask = newDeadPixelsMask(msr, threshold)

    % Define common window and message strings
    fname = 'newDeadPixelsMask';
    window_title = 'RCT Analyze Raw Film: New Dead Pixels Mask';
    progress_tracker_title = 'New Dead Pixels Mask';

    % Validate input arguments
    if(~isMeasurementDataStruct(msr))
        error('%s: Invalid data or measurement not set.', fname);

    endif;

    if(~isBackgroundDataStruct(msr.background))
        error('%s: Invalid data or background data set not set.', fname);

    endif;

    validateattributes( ...
        threshold, ...
        {'float'}, ...
        {'scalar', '>=', 0, '<=', 1}, ...
        fname, ...
        'threshold' ...
        );

    % Display information on the calculation progress
    progress_tracker = waitbar( ...
        0.0, ...
        'Calculating ...', ...
        'name', progress_tracker_title ...
        );

    % Initialize loop counter
    idx = 1;

    % Allocate memory for storing mask pixels
    pixel_data = ones(size(msr.background.pixel_data));

    % Accumulate dead pixels
    while(numel(msr.background.file_list) >= idx)
        img = imread(msr.background.file_list{idx});

        % Smooth out pixel data again if required
        smoothed = zeros(size(img));
        if(isequal('median', msr.pixel_data_smoothing.method))
            % Load required package
            pkg load image;

            % Smooth data using median filter
            smoothed(:, :, 1) = medfilt2( ...
                img(:, :, 1), ...
                msr.pixel_data_smoothing.window ...
                );
            smoothed(:, :, 2) = medfilt2( ...
                img(:, :, 2), ...
                msr.pixel_data_smoothing.window ...
                );
            smoothed(:, :, 3) = medfilt2( ...
                img(:, :, 3), ...
                msr.pixel_data_smoothing.window ...
                );

            % Unload loaded package
            pkg unload image;

        elseif(isequal('wiener', msr.pixel_data_smoothing.method))
            % Load required package
            pkg load image;

            % Smooth data using wiener filter
            smoothed(:, :, 1) = wiener2( ...
                img(:, :, 1), ...
                msr.pixel_data_smoothing.window ...
                );
            smoothed(:, :, 2) = wiener2( ...
                img(:, :, 2), ...
                msr.pixel_data_smoothing.window ...
                );
            smoothed(:, :, 3) = wiener2( ...
                img(:, :, 3), ...
                msr.pixel_data_smoothing.window ...
                );

            % Unload loaded package
            pkg unload image;

        else
            smoothed = img;

        endif;

        red_mask   = smoothed(:, :, 1) > ((1 - threshold)*(intmax('uint16') - 1));
        green_mask = smoothed(:, :, 2) > ((1 - threshold)*(intmax('uint16') - 1));
        blue_mask  = smoothed(:, :, 3) > ((1 - threshold)*(intmax('uint16') - 1));
        pixel_data(:, :, 1) = pixel_data(:, :, 1).*red_mask;
        pixel_data(:, :, 2) = pixel_data(:, :, 2).*green_mask;
        pixel_data(:, :, 3) = pixel_data(:, :, 3).*blue_mask;

        waitbar( ...
            idx/numel(msr.background.file_list), ...
            progress_tracker ...
            );

        idx = idx + 1;

    endwhile;

    % Kill calculation progress tracker
    if(ishandle(progress_tracker))
        delete(progress_tracker);

    endif;

    % Fill the return structure with calculated data
    dead_pixels_mask            = struct();
    dead_pixels_mask.threshold  = threshold;
    dead_pixels_mask.pixel_data = pixel_data;

endfunction;

function result = isDeadPixelsMaskStruct(dpm)
    result = false;
    if( ...
            isstruct(dpm) ...
            && isfield(dpm, 'threshold') ...
            && isfield(dpm, 'pixel_data') ...
            && isscalar(dpm.threshold) ...
            && isfloat(dpm.threshold) ...
            && ~isempty(dpm.pixel_data) ...
            && (3 == size(dpm.pixel_data, 3)) ...
            && ismatrix(dpm.pixel_data(:, :, 1)) ...
            && ismatrix(dpm.pixel_data(:, :, 2)) ...
            && ismatrix(dpm.pixel_data(:, :, 3)) ...
            )
        result = true;

    endif;

endfunction;

% -----------------------------------------------------------------------------
%
% Optical Density Data Structure Routines
%
% -----------------------------------------------------------------------------
function measurement = calculateOpticalDensity(measurement)

    % Define common window and message strings
    fname = 'calculateOpticalDensity';
    window_title = 'RCT Analyze Raw Film: Calculate Optical Density';

    % Initialize data structures for keeping computation results
    optical_density = struct();
    pixel_data = [];

    % Check for reference dataset ('irradiated')
    if(~isfield(measurement, 'irradiated') || isnan(measurement.irradiated))
        % Reference dataset is missing. Display error messages and abort loading
        msgbox( ...
            { ...
                'Missing reference dataset (\"Irradiated\").', ...
                'Aborting calculation ...' ...
                }, ...
            window_title, ...
            'error' ...
            );

        % also send message to the workspace
        fprintf( ...
            stderr(), ...
            '%s: Missing reference dataset (\"Irradiated\"). Aborting calculation ...\n', ...
            fname ...
            );

        % Abort loading the scanset
        return;

    endif;

    % Check for reference dataset ('background')
    if(~isfield(measurement, 'background') || isnan(measurement.background))
        % Reference dataset is missing. Display error messages and abort loading
        msgbox( ...
            { ...
                'Missing reference dataset (\"Background\").', ...
                'Aborting calculation ...' ...
                }, ...
            window_title, ...
            'error' ...
            );

        % also send message to the workspace
        fprintf( ...
            stderr(), ...
            '%s: Missing reference dataset (\"Background\"). Aborting calculation ...\n', ...
            fname ...
            );

        % Abort loading the scanset
        return;

    endif;

    % Allocate memory for optical density values
    pixel_data = zeros(size(measurement.irradiated.pixel_data));

    if( ...
            isfield(measurement, 'zero_light') ...
            && isfield(measurement.zero_light, 'pixel_data') ...
            )
        I0 = ...
            measurement.background.pixel_data ...
            - measurement.zero_light.pixel_data;
        It = ...
            measurement.irradiated.pixel_data ...
            - measurement.zero_light.pixel_data;

    else
        I0 = measurement.background.pixel_data;
        It = measurement.irradiated.pixel_data;

    endif;

    % Calculate optical density
    pixel_data = log10(I0./It);

    % Fill the return structure with calculated data
    optical_density.pixel_data = pixel_data;

    measurement.optical_density = optical_density;

endfunction;

% -----------------------------------------------------------------------------
%
% Function 'rms' - calculate a RMS value for the given array of numbers
%
% -----------------------------------------------------------------------------
function result = rms(X)
    result = [0; 0; 0];
    result(1) = sqrt(sum(sum(X(:, :, 1).*X(:, :, 1)))/numel(X(:, :, 1)));
    result(2) = sqrt(sum(sum(X(:, :, 2).*X(:, :, 2)))/numel(X(:, :, 2)));
    result(3) = sqrt(sum(sum(X(:, :, 3).*X(:, :, 1)))/numel(X(:, :, 3)));

endfunction;

% -----------------------------------------------------------------------------
%
% Function 'renderImageFrom2DMatrix' - render 2D matrix data to the data format
% displayable on the screen
%
% -----------------------------------------------------------------------------
function I = renderImageFromMatrix(M)

    % Load required packages
    pkg load image;

    I = mat2gray(M);

    % Unload loaded packages
    pkg unload image;

endfunction;

% -----------------------------------------------------------------------------
%
% Function 'renderImageFrom3DMatrix' - Render 3D matrix data to the data format
% displayable on the screen
%
% -----------------------------------------------------------------------------
function I = renderImageFrom3DMatrix(M)

    % Load required packages
    pkg load image;

    I = cat( ...
        3, ...
        mat2gray(M(:, :, 1)), ...
        mat2gray(M(:, :, 2)), ...
        mat2gray(M(:, :, 3)) ...
        );

    % Unload loaded packages
    pkg unload image;

endfunction;




% =============================================================================
%
% GUI Creation Section
%
% =============================================================================

% -----------------------------------------------------------------------------
%
% Function 'buildGUI'
%
% -----------------------------------------------------------------------------
function [app] = buildGUI(app)

    % Allocate structure for storing gui elemnents ----------------------------
    gui = struct();

    % Create main figure ------------------------------------------------------
    gui.main_figure = figure( ...
        'name', 'RCT Analyze Film', ...
        'tag', 'main_figure', ...
        'menubar', 'none', ...
        'sizechangedfcn', @uiResize, ...
        'position', uiCalculateInitialPosition(get(0, 'ScreenSize')) ...
        );

    % Create custom menu bar --------------------------------------------------

    % Create file menu and file menu entries
    gui.file_menu = uimenu( ...
        'parent', gui.main_figure, ...
        'tag', 'file_menu', ...
        'label', '&File', ...
        'accelerator', 'f' ...
        );
    gui.fm_load_background = uimenu( ...
        'parent', gui.file_menu, ...
        'tag', 'fm_load_background', ...
        'label', 'Load Ba&ckground Scans', ...
        'accelerator', 'c', ...
        'callback', @(src, evt)uiLoadScanset('background') ...
        );
    gui.fm_load_irradiated = uimenu( ...
        'parent', gui.file_menu, ...
        'tag', 'fm_load_irradiated', ...
        'label', 'Load &Irradiated Scans', ...
        'accelerator', 'i', ...
        'callback', @(src, evt)uiLoadScanset('irradiated') ...
        );
    gui.fm_load_zerolight = uimenu( ...
        'parent', gui.file_menu, ...
        'tag', 'fm_load_zerolight', ...
        'label', 'Load Zero &Light Scans', ...
        'accelerator', 'l', ...
        'callback', @(src, evt)uiLoadScanset('zerolight') ...
        );
    gui.fm_exportto_workspace = uimenu( ...
        'parent', gui.file_menu, ...
        'tag', 'fm_exportto_workspace', ...
        'label', 'Export to &Workspace', ...
        'accelerator', 'w', ...
        'separator', 'on', ...
        'callback', @(src, evt)uiExportTo('workspace') ...
        );
    gui.fm_exportto_file = uimenu( ...
        'parent', gui.file_menu, ...
        'tag', 'fm_exportto_file', ...
        'label', 'Export to Fil&e', ...
        'accelerator', 'e', ...
        'callback', @(src, evt)uiExportTo('file') ...
        );
    gui.fm_quit = uimenu( ...
        'parent', gui.file_menu, ...
        'tag', 'fm_quit', ...
        'label', '&Quit', ...
        'accelerator', 'q', ...
        'separator', 'on', ...
        'callback', @uiQuit ...
        );

    % Create help menu and help menu entries
    gui.help_menu = uimenu( ...
        'parent', gui.main_figure, ...
        'tag', 'help_menu', ...
        'label', '&Help', ...
        'accelerator', 'h' ...
        );
    gui.hm_help = uimenu( ...
        'parent', gui.help_menu, ...
        'tag', 'hm_help', ...
        'label', 'Help on &Application', ...
        'accelerator', 'a', ...
        'enable', 'off', ...
        'callback', @uiAppHelp ...
        );
    gui.hm_about = uimenu( ...
        'parent', gui.help_menu, ...
        'tag', 'hm_about', ...
        'label', 'A&bout', ...
        'accelerator', 'b', ...
        'separator', 'on', ...
        'enable', 'off', ...
        'callback', @uiAppAbout ...
        );

    % Create main panel -------------------------------------------------------
    gui.main_panel = uipanel( ...
        'parent', gui.main_figure, ...
        'tag', 'main_panel', ...
        'bordertype', 'none', ...
        'position', [0, 0, 1, 1] ...
        );

    % % Define dimensions for panel elements with fixed size
    gui.padding = 5;
    gui.control_panel_width = 300;

    % Calculate normalized position of main panel elements
    position = uiMainPanelElementsPosition(gui);

    % Create main panel elements ----------------------------------------------

    % ROI panel
    gui.roi_panel = uipanel( ...
        'parent', gui.main_panel, ...
        'tag', 'roi_panel', ...
        'title', 'ROI Data View', ...
        'position', position(1, :) ...
        );

    % Scans view panel
    gui.scans_panel = uipanel( ...
        'parent', gui.main_panel, ...
        'tag', 'scans_panel', ...
        'title', 'Scan View', ...
        'position', position(2, :) ...
        );

    % Control panel
    gui.control_panel = uipanel( ...
        'parent', gui.main_panel, ...
        'tag', 'control_panel', ...
        'title', 'Control Panel', ...
        'position', position(3, :) ...
        );

    % Create ROI panel elements -----------------------------------------------

    % Divide ROI panel into two panels: one for table view, and other for ROI
    % selection control ('Undo' button)
    gui.roi_control_width = 100;
    position = uiROIPanelElementsPosition(gui);

    % Create ROI data panel
    gui.roi_data_panel = uipanel( ...
        'parent', gui.roi_panel, ...
        'tag', 'roi_data_panel', ...
        'bordertype', 'none', ...
        'position', position(1, :) ...
        );

    % Create ROI control panel
    gui.roi_control_panel = uipanel( ...
        'parent', gui.roi_panel, ...
        'tag', 'roi_control_panel', ...
        'bordertype', 'none', ...
        'position', position(2, :) ...
        );

    % Create ROI data panel elements ------------------------------------------
    gui.roi_data_view = uitable( ...
        'parent', gui.roi_data_panel, ...
        'ColumnName', {'ROI Center [px]', 'ROI Center [mm]', 'Intensity (R, G, B)'}, ...
        'units', 'normalized', ...
        'position', [0, 0, 1, 1] ...
        );

    % Create ROI control panel elements ---------------------------------------
    gui.roi_control_undo_height = 30;
    position = uiROIControlPanelElementsPosition(gui);
    gui.roi_control_undo = uicontrol( ...
        'parent', gui.roi_control_panel, ...
        'style', 'pushbutton', ...
        'tag', 'roi_control_undo', ...
        'string', 'Undo ROI', ...
        'tooltipstring', 'Undo last ROI selection', ...
        'callback', @uiUndoROISelection, ...
        'units', 'normalized', ...
        'position', position(1, :) ...
        );

    % Create scans view elements ----------------------------------------------
    gui.scans_landscape_view = false;
    position = uiScansPanelElementsPosition(gui);

    % Create panels
    gui.scans_background_panel = uipanel( ...
        'parent', gui.scans_panel, ...
        'tag', 'scans_background_panel', ...
        'title', 'Background Signal View', ...
        'position', position(1, :) ...
        );
    gui.scans_irradiated_panel = uipanel( ...
        'parent', gui.scans_panel, ...
        'tag', 'scans_irradiated_panel', ...
        'title', 'Irradiated Signal View', ...
        'position', position(2, :) ...
        );
    gui.scans_zerolight_panel = uipanel( ...
        'parent', gui.scans_panel, ...
        'tag', 'scans_zerolight_panel', ...
        'title', 'Zero Light Signal View', ...
        'position', position(3, :) ...
        );
    gui.scans_deadpixels_panel = uipanel( ...
        'parent', gui.scans_panel, ...
        'tag', 'scans_deadpixels_panel', ...
        'title', 'Dead Pixels View', ...
        'position', position(4, :) ...
        );
    gui.scans_opticaldensity_panel = uipanel( ...
        'parent', gui.scans_panel, ...
        'tag', 'scans_opticaldensity_panel', ...
        'title', 'Optical Density View', ...
        'position', position(5, :) ...
        );

    % Create views
    gui.scans_background_view = axes( ...
        'parent', gui.scans_background_panel, ...
        'tag', 'scans_background_view', ...
        'position', [0 0 1 1] ...
        );
    % cla(gui.scans_background_view);
    text( ...
        'parent', gui.scans_background_view, ...
        0.5, 0.5, ...
        'No data loaded!', ...
        'horizontalalignment', 'center', ...
        'verticalalignment', 'middle' ...
        );
    axis(gui.scans_background_view, 'off');
    gui.scans_irradiated_view = axes( ...
        'parent', gui.scans_irradiated_panel, ...
        'tag', 'scans_irradiated_view', ...
        'position', [0 0 1 1] ...
        );
    % cla(gui.scans_irradiated_view);
    text( ...
        'parent', gui.scans_irradiated_view, ...
        0.5, 0.5, ...
        'No data loaded!', ...
        'horizontalalignment', 'center', ...
        'verticalalignment', 'middle' ...
        );
    axis(gui.scans_irradiated_view, 'off');
    gui.scans_zerolight_view = axes( ...
        'parent', gui.scans_zerolight_panel, ...
        'tag', 'scans_zerolight_view', ...
        'position', [0 0 1 1] ...
        );
    % cla(gui.scans_izerolight_view);
    text( ...
        'parent', gui.scans_zerolight_view, ...
        0.5, 0.5, ...
        'No data loaded!', ...
        'horizontalalignment', 'center', ...
        'verticalalignment', 'middle' ...
        );
    axis(gui.scans_zerolight_view, 'off');
    gui.scans_deadpixels_view = axes( ...
        'parent', gui.scans_deadpixels_panel, ...
        'tag', 'scans_deadpixels_view', ...
        'position', [0 0 1 1] ...
        );
    % cla(gui.scans_deadpixels_view);
    text( ...
        'parent', gui.scans_deadpixels_view, ...
        0.5, 0.5, ...
        'No data loaded!', ...
        'horizontalalignment', 'center', ...
        'verticalalignment', 'middle' ...
        );
    axis(gui.scans_deadpixels_view, 'off');
    gui.scans_opticaldensity_view = axes( ...
        'parent', gui.scans_opticaldensity_panel, ...
        'tag', 'scans_opticaldensity_view', ...
        'position', [0 0 1 1] ...
        );
    % cla(gui.scans_opticaldensity_view);
    text( ...
        'parent', gui.scans_opticaldensity_view, ...
        0.5, 0.5, ...
        'No data loaded!', ...
        'horizontalalignment', 'center', ...
        'verticalalignment', 'middle' ...
        );
    axis(gui.scans_opticaldensity_view, 'off');

    % Create control panel elements -------------------------------------------

    % Save gui data -----------------------------------------------------------
    app.gui = gui;

endfunction;

% -----------------------------------------------------------------------------
%
% Function 'uiCalculateInitialPosition'
%
% -----------------------------------------------------------------------------
function ui_position = uiCalculateInitialPosition(screen_size)

    % Init return value to default
    ui_position = [100 100 400 400];

    % Make app occupy upt to 80% of the available screen size
    ui_width = round(screen_size(3)*0.80);
    ui_height = round(screen_size(4)*0.80);
    ui_x_origin = floor((screen_size(3) - ui_width)*0.5);
    ui_y_origin = floor((screen_size(4) - ui_height)*0.5);

    % Update return value
    ui_position = [ui_x_origin, ui_y_origin, ui_width, ui_height];

endfunction;

% -----------------------------------------------------------------------------
%
% Function 'uiMainPanelElementsPosition'
%
% -----------------------------------------------------------------------------
function position = uiMainPanelElementsPosition(gui_handle)

    % Init return value
    position = [];

    % Calculate elements position
    mainpanel_extents = getpixelposition(gui_handle.main_panel);
    width  = mainpanel_extents(3) - mainpanel_extents(1);
    height = mainpanel_extents(4) - mainpanel_extents(2);
    rel_control_panel_width = gui_handle.control_panel_width/width;
    roi_view = [0, 0, 1 - rel_control_panel_width, 0.25];
    scan_view = [0, roi_view(4), roi_view(3), 1 - roi_view(4)];
    control_view = [roi_view(3), 0, 1 - roi_view(3), 1];

    % Update return variable
    position = [position; roi_view; scan_view; control_view];

endfunction;

% -----------------------------------------------------------------------------
%
% Function 'uiROIPanelElementsPosition'
%
% -----------------------------------------------------------------------------
function position = uiROIPanelElementsPosition(gui_handle)

    % Init return value
    position = [];

    % Calculate elements position
    roi_panel_extents = getpixelposition(gui_handle.roi_panel);
    width  = roi_panel_extents(3) - roi_panel_extents(1);
    height = roi_panel_extents(4) - roi_panel_extents(2);
    rel_hpadding = gui_handle.padding/width;
    rel_vpadding = gui_handle.padding/height;
    data_view = [0, 0, 0.75 - rel_hpadding, 1];
    control_view = [ ...
        data_view(3) + rel_hpadding, ...
        rel_vpadding, ...
        1 - data_view(3) - 2*rel_hpadding, ...
        1 - 2*rel_vpadding ...
        ];

    % Update return variable
    position = [data_view; control_view];

endfunction;

% -----------------------------------------------------------------------------
%
% Function 'uiROIControlPanelElementsPosition'
%
% -----------------------------------------------------------------------------
function position = uiROIControlPanelElementsPosition(gui_handle);

    % Init return value
    position = [];

    % Calculate elements position
    roi_controlpanel_extents = getpixelposition(gui_handle.roi_control_panel);
    width  = roi_controlpanel_extents(3) - roi_controlpanel_extents(1);
    height = roi_controlpanel_extents(4) - roi_controlpanel_extents(2);
    undo_rel_height = gui_handle.roi_control_undo_height/height;
    undo_push = [0, 1 - undo_rel_height, 1, undo_rel_height];

    % Update return variable
    position = [undo_push;];

endfunction;

% -----------------------------------------------------------------------------
%
% Function 'uiScansPanelElementsPosition'
%
% -----------------------------------------------------------------------------
function position = uiScansPanelElementsPosition(gui_handle)

    % Init return value
    position = [];

    % Calculate elements position based on scan orientation
    if(gui_handle.scans_landscape_view)
        background      = [0, 1 - 1*0.2, 1, 0.2];
        irradiated      = [0, 1 - 2*0.2, 1, 0.2];
        zerolight       = [0, 1 - 3*0.2, 1, 0.2];
        deadpixels      = [0, 1 - 4*0.2, 1, 0.2];
        opticaldensity  = [0, 1 - 5*0.2, 1, 0.2];

    else
        background      = [0*0.2, 0, 0.2, 1];
        irradiated      = [1*0.2, 0, 0.2, 1];
        zerolight       = [2*0.2, 0, 0.2, 1];
        deadpixels      = [3*0.2, 0, 0.2, 1];
        opticaldensity  = [4*0.2, 0, 0.2, 1];

    endif;

    % Update return variable
    position = [ ...
        position; ...
        background; ...
        irradiated; ...
        zerolight; ...
        deadpixels; ...
        opticaldensity ...
        ];

endfunction;



% =============================================================================
%
% GUI Callbacks Section
%
% =============================================================================

% -----------------------------------------------------------------------------
%
% Menu Bar Callbacks Section
%
% -----------------------------------------------------------------------------
function uiLoadScanset(scantype)
    % TODO: Add function implementation here
    % utl_gui_file_multiselect();
    % rct_load_scanset(fnames);

endfunction;

function uiExportTo(destination)
    % TODO: Add function implementation here

endfunction;

function uiQuit(src, evt)
    close(gcf());

endfunction;

function uiAppHelp(src, evt)
    % TODO: Add function implementation here

endfunction;

function uiAppAbout(src, evt)
    % TODO: Add function implementation here

endfunction;

% -----------------------------------------------------------------------------
%
% Main Panel Callbacks Section
%
% -----------------------------------------------------------------------------
function uiResize(src, evt)

    % Retrieve handle to app data
    app = guidata(src);

    % Recalculate GUI elements position inside main panel
    position = uiMainPanelElementsPosition(app.gui);
    set(app.gui.roi_panel, 'position', position(1, :));
    set(app.gui.scans_panel, 'position', position(2, :));
    set(app.gui.control_panel, 'position', position(3, :));

    % Recalculate GUI elements position inside ROI panel
    position = uiROIPanelElementsPosition(app.gui);
    set(app.gui.roi_data_panel, 'position', position(1, :));
    set(app.gui.roi_control_panel, 'position', position(2, :));

    % Recalculate GUI elements position inside ROI control panel
    position = uiROIControlPanelElementsPosition(app.gui);
    set(app.gui.roi_control_undo, 'position', position(1, :));

    % Recalculate GUI elements position inside Scans panel
    % position = uiScansPanelElementsPosition(app.gui);
    % set(app.gui.scans_background_panel, 'position', position(1, :));
    % set(app.gui.scans_irradiated_panel, 'position', position(2, :));
    % set(app.gui.scans_zerolight_panel, 'position', position(3, :));
    % set(app.gui.scans_deadpixels_panel, 'position', position(4, :));
    % set(app.gui.scans_opticaldensity_panel, 'position', position(5, :));

endfunction;


% -----------------------------------------------------------------------------
%
% ROI Panel Callbacks Section
%
% -----------------------------------------------------------------------------
function uiUndoROISelection(src, evt)
    % TODO: Add function implementation here

endfunction;


% -----------------------------------------------------------------------------
%
% Scans Panel Callbacks Section
%
% -----------------------------------------------------------------------------
