function CAX = find_profile_cax(lE, rE)
% -----------------------------------------------------------------------------
%
% Function 'find_profile_cax':
%
% Use:
%       -- CAX = find_profile_cax(lE, rE)
%
% Description:
%       Find (calculate) beam profile CAX position from the coordiantes of the
%       left and right profile edge.
%
%       lE  floating point value representing coordinate of the left profile
%           edge for the given input data.
%
%       rE  floating point value representing coordinate of the right profile
%           edge for the given input data.
%
%       At all times following relation must be satisfied rE >= lE.
%
% -----------------------------------------------------------------------------
    fname = 'find_profile_cax';
    use_case_a = sprintf('-- CAX = %s(lE, rE)', fname);

    % Validate number of passed arguments
    if(2 ~= nargin)
        % Invalid call to function
        error( ...
            'Invalid call to %s. Correct usage is:\n%s', ...
            fname, ...
            use_case_a ...
            );

    endif;

    % Validate lE
    validateattributes( ...
        lE, ...
        {'float'}, ...
        { ...
            'nonempty', ...
            'scalar', ...
            'finite', ...
            'real' ...
            }, ...
        fname, ...
        'lE' ...
        );

    % Validate rE
    validateattributes( ...
        rE, ...
        {'float'}, ...
        { ...
            'nonempty', ...
            'scalar', ...
            'finite', ...
            'real' ...
            }, ...
        fname, ...
        'rE' ...
        );

    if(lE > rE)
        error( ...
            '%s: Position of the right edge can not be left to the left edge (lE > rE)', ...
            fname ...
            );

    endif;

    CAX = lE + (rE - lE)/2;

endfunction;
