function [master, slave] = runMasterSlave()

hmstrfig = figure('name', 'Master');
hmstrbtn1 = uicontrol( ...
    'parent', hmstrfig, ...
    'string', 'Enable', ...
    'units', 'normalized', ...
    'position', [0.0, 0.66, 1.0, 1.0 - 0.66] ...
    );
hmstrbtn2 = uicontrol( ...
    'parent', hmstrfig, ...
    'string', 'Disable', ...
    'units', 'normalized', ...
    'position', [0.0, 0.33, 1.0, 0.33] ...
    );
hmstrbtn3 = uicontrol( ...
    'parent', hmstrfig, ...
    'string', 'Inactivate', ...
    'units', 'normalized', ...
    'position', [0.0, 0.0, 1.0, 0.33] ...
    );

hslvfig = figure('parent', hmstrfig, 'name', 'Slave');
hslvbtn1 = uicontrol( ...
    'parent', hslvfig, ...
    'string', 'Button 1', ...
    'units', 'normalized', ...
    'position', [0.0, 0.5, 1.0, 0.5] ...
    );
hslvbtn2 = uicontrol( ...
    'parent', hslvfig, ...
    'string', 'Button 2', ...
    'units', 'normalized', ...
    'position', [0.0, 0.0, 1.0, 0.5] ...
    );

master = masterController(hmstrfig, hmstrbtn1, hmstrbtn2, hmstrbtn3, hslvfig);
slave = slaveController(hslvfig, hslvbtn1, hslvbtn2, hmstrfig);
set(hmstrbtn1, 'callback', {master, 'clicked', slave});
set(hmstrbtn2, 'callback', {master, 'clicked', slave});
set(hmstrbtn3, 'callback', {master, 'clicked', slave});
set(hslvbtn1, 'callback', {slave, 'clicked'});
set(hslvbtn2, 'callback', {slave, 'clicked'});

endfunction;
