ui_layout_guides_version = '1.0';

% -----------------------------------------------------------------------------
%
% Function 'newUiLayoutGuides':
%
% Use:
%       -- guides = newUiLayoutGuides()
%
% Description:
%
% TODO: Add function description here
% -----------------------------------------------------------------------------
function guides = newUiLayoutGuides(pad=6, cwd=128, rhg=24, bwd=128)

    % Store function name into variable
    % for easier management of error messages ---------------------------------
    fname = 'newUiLayoutGuides';
    use_case = ' -- guides = newUiLayoutGuides(pad, cwd, rhg, bwd)';

    % Validate input arguments ------------------------------------------------

    % Validate number of input arguments
    if(4 < nargin)
        error( ...
            'Invalid call to %s.  Correct usage is:\n%s\n%s\n%s', ...
            fname, ...
            use_case ...
            );

    endif;

    % Validate arguments
    validateattributes( ...
        pad, ...
        {'float'}, ...
        {'scalar', '>=', 1}, ...
        fname, ...
        'pad' ...
        );
    validateattributes( ...
        cwd, ...
        {'float'}, ...
        {'scalar', '>=', 1}, ...
        fname, ...
        'cwd' ...
        );
    validateattributes( ...
        rhg, ...
        {'float'}, ...
        {'scalar', '>=', 1}, ...
        fname, ...
        'rhg' ...
        );
    validateattributes( ...
        bwd, ...
        {'float'}, ...
        {'scalar', '>=', 1}, ...
        fname, ...
        'bwd' ...
        );

    guides = struct();
    guides.padding_px = pad;
    guides.column_width_px = cwd;
    guides.row_height_px = rhg;
    guides.btn_width_px = bwd;

endfunction;

% -----------------------------------------------------------------------------
%
% Function 'isUiLayoutGuidesStructure':
%
% Use:
%       -- result = isUiLayoutGuidesStructure(obj)
%
% Description:
%
% TODO: Add function description here
% -----------------------------------------------------------------------------
function result = isUiLayoutGuidesStructure(obj)

    % Store function name into variable
    % for easier management of error messages ---------------------------------
    fname = 'isUiLayoutGuidesStructure';
    use_case = ' -- result = isUiLayoutGuidesStructure(obj)';

    % Validate input arguments ------------------------------------------------

    % Validate number of input arguments
    if(1 ~= nargin)
        error( ...
            'Invalid call to %s.  Correct usage is:\n%s\n%s\n%s', ...
            fname, ...
            use_case ...
            );

    endif;

    % Initialize return value to default
    result = false;

    if( ...
            isstruct(obj) ...
            && isfield(obj, 'padding_px') ...
            && isscalar(obj.padding_px) ...
            && isfloat(obj.padding_px) ...
            && (0 < obj.padding_px) ...
            && isfield(obj, 'column_width_px') ...
            && isscalar(obj.column_width_px) ...
            && isfloat(obj.column_width_px) ...
            && (0 < obj.column_width_px) ...
            && isfield(obj, 'row_height_px') ...
            && isscalar(obj.row_height_px) ...
            && isfloat(obj.row_height_px) ...
            && (0 < obj.row_height_px) ...
            && isfield(obj, 'btn_width_px') ...
            && isscalar(obj.btn_width_px) ...
            && isfloat(obj.btn_width_px) ...
            && (0 < obj.btn_width_px) ...
            )

        result = true;

    endif;

endfunction;
