classdef DataSample
%% ----------------------------------------------------------------------------
%%
%% Class 'DataSample':
%%
%% ----------------------------------------------------------------------------
%
%% Description:
%       Data structure representing one sampled pixel area from the image (i.e.
%       optical density). One data sample is represented by coordinates of
%       the center of sampled area (row and column), size of sampled area
%       (window) in points (pixels), number of data samples inside the sampled
%       area (i.e. number of points), mean pixel value and standard deviation of
%       pixel values.
%
%       'DataSample' class instances have following properties:
%
%       position: two-element row vestor, def. [0 0]
%           Coordinates of the center of sampled pixel area [row column].
%           Sample coordinates don't have to represent exact center of the
%           sampled image are, especially at the image bordes where clippig can
%           occur.
%
%       window: two-element row vector, def. [0 0]
%           Size of the sampled area (in pixels). The format is [length width].
%
%       n: double, def. 0
%           Number of sampled pixels.
%
%       value: double, def. []
%           Mean pixel value per color channel of the sampled pixels.
%
%       stdev: double, def. []
%           Standard deviation from mean value of the sampled pixel values.
%
%  ----------------------------------------------------------------------------

    properties (SetAccess = private, GetAccess = public)
%%  ---------------------------------------------------------------------------
%%
%%  Properties section
%%
%%  ---------------------------------------------------------------------------
        position = [];
        window   = [];
        n        = 0;
        value    = [];
        stdev    = [];

    endproperties;


    methods (Access = public)
%%  ---------------------------------------------------------------------------
%%
%%  Public methods section
%%
%%  ---------------------------------------------------------------------------

        function ds = DataSample(varargin)
%  ----------------------------------------------------------------------------
%
%  Method 'DataSample':
%
%  Use:
%       -- ds = DataSample(position, window, value, stdev)
%       -- ds = DataSample(other)
%
%  Description:
%          Class constructor.
%
%  ----------------------------------------------------------------------------
            fname = 'DataSample';
            use_case_a = sprintf( ...
                cstrcat( ...
                    ' -- ds = ', ...
                    '%s(position, window, n, value, stdev)' ...
                    ), ...
                fname ...
                );
            use_case_b = sprintf(' -- ds = %s(other)', fname);

            if(1 == nargin)
                % Copy constructor invoked
                if(isa(varargin{1}, 'DataSample'))
                    ds.position = varargin{1}.position;
                    ds.window   = varargin{1}.window;
                    ds.n        = varargin{1}.n;
                    ds.value    = varargin{1}.value;
                    ds.stdev    = varargin{1}.stdev;

                else
                    error( ...
                        sprintf( ...
                            cstrcat( ...
                                '%s: other must be an instance of the', ...
                                ' "DataSample" class' ...
                                ), ...
                            fname ...
                            ) ...
                        );

                endif;

            elseif(5 == nargin)
                % Regular constructor invoked

                % Validate position argument
                validateattributes( ...
                    varargin{1}, ...
                    {'float'}, ...
                    { ...
                        'row', ...
                        'finite', ...
                        'nonempty', ...
                        'nonnan', ...
                        'numel', 2, ...
                        '>=', 1, ...
                        }, ...
                    fname, ...
                    'position' ...
                    );

                % Validate window argument
                validateattributes( ...
                    varargin{2}, ...
                    {'float'}, ...
                    { ...
                        'row', ...
                        'finite', ...
                        'nonempty', ...
                        'nonnan', ...
                        'numel', 2, ...
                        '>=', 1, ...
                        }, ...
                    fname, ...
                    'window' ...
                    );

                % Validate value supplied for number of samples
                validateattributes( ...
                    varargin{3}, ...
                    {'float'}, ...
                    { ...
                        'scalar', ...
                        'finite', ...
                        'nonempty', ...
                        'nonnan', ...
                        '>=', 1, ...
                        }, ...
                    fname, ...
                    'n' ...
                    );

                % Validate value argument
                validateattributes( ...
                    varargin{4}, ...
                    {'float'}, ...
                    { ...
                        'row', ...
                        'finite', ...
                        'nonempty', ...
                        'nonnan', ...
                        '>=', 0, ...
                        }, ...
                    fname, ...
                    'value' ...
                    );

                % Check if value vector has proper number of elements (i.e. 1
                % element for single channel image and 3 elements for fullcolor
                % image.
                if(1 ~= numel(varargin{4}) && 3 ~= numel(varargin{4}))
                    error( ...
                        sprintf( ...
                            cstrcat( ...
                                '%s: value must be one, or three elements', ...
                                ' row vector (got %d elements)' ...
                                ), ...
                            fname, ...
                            numel(varargin{4}) ...
                            ) ...
                        );
                endif;  % 1 ~= numel(varargin{4}) && 3 ~= numel(varargin{4})

                % Validate stdev argument
                validateattributes( ...
                    varargin{5}, ...
                    {'float'}, ...
                    { ...
                        'row', ...
                        'finite', ...
                        'nonempty', ...
                        'nonnan', ...
                        '>=', 0, ...
                        }, ...
                    fname, ...
                    'stdev' ...
                    );

                % Check if stdev vector has proper number of elements (i.e. 1
                % element for single channel image and 3 elements for fullcolor
                % image.
                if(1 ~= numel(varargin{5}) && 3 ~= numel(varargin{5}))
                    error( ...
                        sprintf( ...
                            cstrcat( ...
                                '%s: value must be one, or three elements', ...
                                ' row vector (got %d elements)' ...
                                ), ...
                            fname, ...
                            numel(varargin{5}) ...
                            ) ...
                        );
                endif;  % 1 ~= numel(varargin{4}) && 3 ~= numel(varargin{4})

                % Assign argument values to ds object
                ds.position = varargin{1};
                ds.window   = varargin{2};
                ds.n        = varargin{3};
                ds.value    = varargin{4};
                ds.stdev    = varargin{5};

            else
                % Invalid call to constructor
                error( ...
                    'Invalid call to %s. Correct usage is:\n%s\n%s', ...
                    fname, ...
                    use_case_a, ...
                    use_case_b ...
                    );

            endif;  % 0 == nargin

        endfunction;  % DataSample()


        function disp(ds)
%  ----------------------------------------------------------------------------
%
%  Method 'disp':
%
%  Use:
%       -- ds.disp()
%
%  Description:
%          The disp method is used by Octave whenever a instance of the class
%          should be displayed on the screen.
%
%  ----------------------------------------------------------------------------
            % Determine the output format
            strf = '';
            if(1 == numel(ds.value))
                strf = cstrcat(
                    '\tDataSample("%d", "%d", "%d", "%d", "%d", ', ...
                    '"%5.2f", "%5.2f")\n' ...
                    );

            else
                strf = cstrcat(
                    '\tDataSample("%d", "%d", "%d", "%d", "%d", ', ...
                    '"%5.2f", "%5.2f", "%5.2f" ', ...
                    '"%5.2f", "%5.2f", "%5.2f")\n' ...
                    );

            endif;  % 1 == numel(ds.value)

            printf( ...
                strf, ...
                ds.position, ...
                ds.window, ...
                ds.n, ...
                ds.value, ...
                ds.stdev ...
                );

        endfunction;  % disp()


        function dscell = ascell(ds)
% -----------------------------------------------------------------------------
%
% Method 'ascell':
%
% Use:
%       -- dscell = ds.ascell()
%
% Description:
%          Return data sample properties as cell array of strings. This
%          function is required if the class is used as model for the
%          table view.
%
% -----------------------------------------------------------------------------
            dscell = { ...
                sprintf('%d', ds.position(1)), ...
                sprintf('%d', ds.position(2)), ...
                sprintf('%d', ds.window(1)), ...
                sprintf('%d', ds.window(2)), ...
                sprintf('%d', ds.n) ...
                };

            if(1 == numel(ds.value))
                dscell{end + 1} = sprintf('%5.2f', ds.value);
                dscell{end + 1} = sprintf('%5.2f', ds.stdev);

            else
                dscell{end + 1} = sprintf('%5.2f', ds.value(1));
                dscell{end + 1} = sprintf('%5.2f', ds.value(2));
                dscell{end + 1} = sprintf('%5.2f', ds.value(3));
                dscell{end + 1} = sprintf('%5.2f', ds.stdev(1));
                dscell{end + 1} = sprintf('%5.2f', ds.stdev(2));
                dscell{end + 1} = sprintf('%5.2f', ds.stdev(3));

            endif;  % 1 == numel(ds.value)

        endfunction;  % dscell()


function dsrow = asrow(ds)
%  ----------------------------------------------------------------------------
%
%  Method 'asrow':
%
%  Use:
%       -- dsrow = ds.asrow()
%
%  Description:
%          Return ds as row vector.
%
%  ----------------------------------------------------------------------------
            dsrow = [ ...
                ds.position(1), ...
                ds.position(2), ...
                ds.window(1), ...
                ds.window(2), ...
                ds.n ...
            ];

            if(1 == numel(ds.value))
                dsrow(end + 1) = ds.value(1);
                dsrow(end + 1) = ds.stdev(1);

            else
                dsrow(end + 1) = ds.value(1);
                dsrow(end + 1) = ds.value(2);
                dsrow(end + 1) = ds.value(3);
                dsrow(end + 1) = ds.stdev(1);
                dsrow(end + 1) = ds.stdev(2);
                dsrow(end + 1) = ds.stdev(3);

            endif;  % 1 == numel(ds.value)

        endfunction;  % asrow()


        function result = numch(ds)
%  ----------------------------------------------------------------------------
%
%  Method 'numch':
%
%  Use:
%       -- result = ds.numch()
%
%  Description:
%          Return number of color channels in the data sample.
%
%  ----------------------------------------------------------------------------
            result = numel(ds.value);

        endfunction;  % numch()


        function result = stderr(cl=1)
%  ----------------------------------------------------------------------------
%
%  Method 'stderr':
%
%  Use:
%       -- result = ds.stderr()
%       -- result = ds.stderr(cl)
%
%  Description:
%          Return standard error for the given datasample and given confidence
%          level.
%
%          cl: double, def. 1
%              Confidence level. It takes values 1, 2, or 3 for the 1 sigma, 2
%              sigma and 3 sigma confidence level respectively.
%
%  ----------------------------------------------------------------------------
            fname = 'stderr';

            if(0 == sum([1 2 3] == cl))
                error( ...
                    sprintf( ...
                        cstrcat( ...
                            '%s: cl must be 1, 2 or 3 (got %d)' ...
                            ), ...
                        fname, ...
                        cl ...
                        ) ...
                    );

            endif;  % cl ~= 1, 2, 3

            result = (cl * ds.stdev) / sqrt(ds.n);

        endfunction;


        function result = isequivalent(ds, other)
%  ----------------------------------------------------------------------------
%
%  Method 'isequivalent':
%
%  Use:
%       -- result = ds.isequivalent(other)
%
%  Description:
%          Return whether or not two data samples are equivalent.
%          Two data samples are equivalent if they have equal windows, and their
%          value and stdev vectors have the same number of elements.
%
%  ----------------------------------------------------------------------------
            fname = 'isequivalent';

            if(~isa(other, 'DataSample'))
                error( ...
                    sprintf( ...
                        cstrcat( ...
                            '%s: other must be an instance of the ', ...
                            '"DataSample" class' ...
                            ), ...
                        fname ...
                        ) ...
                    );

            endif;

            % Initialize result to a default value
            result = false;
            if( ...
                    isequal(ds.window, other.window) ...
                    && numel(ds.value) == numel(other.window) ...
                    && numel(ds.stdev) == numel(other.stdev) ...
                    );
                result = true;

            endif;

        endfunction;  % isequivalent()


        function result = isequal(ds, other)
%  ----------------------------------------------------------------------------
%
%  Method 'isequal':
%
%  Use:
%       -- result = ds.isequal(other)
%
%  Description:
%          Return whether or not two data samples are equal. Two data samples
%          are equal if all their properties have equal values. We use machine
%          precision (i.e. eps()) as the criteria if two real numvers are equal
%          (e.g. val1 - val2 <= eps() => two values are equal).
%
%  ----------------------------------------------------------------------------
            fname = 'isequal';

            if(~isa(other, 'DataSample'))
                error( ...
                    sprintf( ...
                        cstrcat( ...
                            '%s: other must be an instance of the ', ...
                            '"DataSample" class' ...
                            ), ...
                        fname ...
                        ) ...
                    );

            endif;

            % Initialize result to a default value
            result = false;
            if( ...
                    isequal(other.position, ds.position) ...
                    && isequal(other.window, ds.window) ...
                    && isequal(other.n, ds.n)  ...
                    && 0 == sum(abs(other.value - ds.value) < eps()) ...
                    && 0 == sum(abs(other.stdev - ds.stdev) < eps()) ...
                    )
                result = true;

            endif;

        endfunction;  % isequal()

    endmethods;

endclassdef;  % DataSample
