% -----------------------------------------------------------------------------
%
% Function 'ItemSelectView':
%
% Use:
%       -- handles = ItemSelectView(hparent, name, uistyle, list)
%
% Description:
%          Panel containing fields for editing items.
%
% -----------------------------------------------------------------------------
function handles = ItemSelectView(hparent, name, uistyle, list)
    fname = 'ItemSelectView';
    use_case_a = ' -- handles = ItemSelectView(hparent, name, uistyle, list)';

    % Validate input arguments ------------------------------------------------
    if(~ishghandle(hparent))
        error( ...
            '%s: hparent must be handle to a graphics object', ...
            fname
            );

    endif;

    if(~ischar(name))  % name can be an empty string
        error( ...
            '%s: name must be a character array', ...
            fname
            );

    endif;

    if(~isa(uistyle, 'AppUiStyle'))
        error( ...
            '%s: uistyle must be an instance of the "AppUiStyle" class', ...
            fname ...
            );

    endif;

    if(~isa(list, 'ItemList'))
        error( ...
            '%s: list must be an instance of the "ItemList" class', ...
            fname ...
            );

    endif;

    % Create the GUI elements -------------------------------------------------
    handles = struct();

    % Create panel containig the view's elements
    handles.main_panel = uipanel( ...
        'parent', hparent, ...
        'title', name, ...
        'position', [0.00, 0.00, 1.00, 1.00] ...
        );

    % Create view's elements

    % Calculate positions of the view's elements
    position = itemSelectViewElementsPosition(handles.main_panel, uistyle);

    % Label: Name
    handles.lbl_name = uicontrol( ...
        'parent', handles.main_panel, ...
        'style', 'text', ...
        'string', 'Item Name', ...
        'horizontalalignment', 'left', ...
        'units', 'normalized', ...
        'position', position(1, :) ...
        );

    % Edit field: Name
    handles.fld_name = uicontrol( ...
        'parent', handles.main_panel, ...
        'style', 'popupmenu', ...
        'enable', 'on', ...
        'string', list.names(), ...
        'value', 1, ...
        'tooltipstring', 'Edit item name', ...
        'horizontalalignment', 'left', ...
        'units', 'normalized', ...
        'position', position(2, :) ...
        );

    % Label: Value
    handles.lbl_value = uicontrol( ...
        'parent', handles.main_panel, ...
        'style', 'text', ...
        'string', 'Item Value', ...
        'horizontalalignment', 'left', ...
        'units', 'normalized', ...
        'position', position(3, :) ...
        );

    % Edit field: Value
    handles.fld_value = uicontrol( ...
        'parent', handles.main_panel, ...
        'style', 'edit', ...
        'enable', 'inactive', ...
        'string', list.at(1).value, ...
        'tooltipstring', 'Edit item value', ...
        'horizontalalignment', 'left', ...
        'units', 'normalized', ...
        'position', position(4, :) ...
        );

endfunction;
