function runMasterSlave()

    hmaster = figure('name', 'Master');
    hbtnl = uicontrol( ...
        'parent', hmaster, ...
        'string', 'Launch Slave', ...
        'units', 'normalized', ...
        'position', [0.00, 0.75, 1.00, 0.25] ...
        );
    hbtne = uicontrol( ...
        'parent', hmaster, ...
        'string', 'Enable', ...
        'units', 'normalized', ...
        'enable', 'off', ...
        'position', [0.00, 0.50, 1.00, 0.25] ...
        );
    hbtnd = uicontrol( ...
        'parent', hmaster, ...
        'string', 'Disable', ...
        'units', 'normalized', ...
        'enable', 'off', ...
        'position', [0.00, 0.25, 1.00, 0.25] ...
        );
    hbtni = uicontrol( ...
        'parent', hmaster, ...
        'string', 'Inactivate', ...
        'units', 'normalized', ...
        'enable', 'off', ...
        'position', [0.00, 0.00, 1.00, 0.25] ...
        );

    master = masterController(hmaster, hbtnl, hbtne, hbtnd, hbtni, NaN);

    set(hbtnl, 'callback', {master, 'clicked', @launchSlave, hmaster});

    setappdata(hmaster, 'controller', master);

endfunction;

function hslave = launchSlave(hmaster)

    hmaster = getappdata(hmaster, 'controller')(NaN, [], 'get', 'hbtnl');
    set(master(NaN, [], 'get', 'hbtnl'), 'enable', 'off');
    set(master(NaN, [], 'get', 'hbtne'), 'enable', 'on');
    set(master(NaN, [], 'get', 'hbtnd'), 'enable', 'on');
    set(master(NaN, [], 'get', 'hbtni'), 'enable', 'on');
    hslave = figure('parent', hmaster, 'name', 'Slave');
    hbtn1 = uicontrol( ...
        'parent', hslave, ...
        'string', 'Button 1', ...
        'units', 'normalized', ...
        'position', [0.00, 0.66, 1.0, 0.34] ...
        );
    hbtn2 = uicontrol( ...
        'parent', hslave, ...
        'string', 'Button 2', ...
        'units', 'normalized', ...
        'position', [0.00, 0.33, 1.0, 0.33] ...
        );
    hbtnc = uicontrol( ...
        'parent', hslave, ...
        'string', 'Close', ...
        'units', 'normalized', ...
        'position', [0.00, 0.00, 1.0, 0.33] ...
        );

    master = master( ...
        master(NaN, [], 'get', 'hparent'), ...
        master(NaN, [], 'get', 'hbtnl'), ...
        master(NaN, [], 'get', 'hbtne'), ...
        master(NaN, [], 'get', 'hbtnd'), ...
        master(NaN, [], 'get', 'hbtni'), ...
        hslave ...
        );
    slave = slaveController(hslave, hbtn1, hbtn2, hbtnc, master(NaN, [], 'get', 'hparent'));

    set(hbtnl, 'callback', {@launchSlave, master});
    set(master(NaN, [], 'get', 'hbtne'), 'callback', {master, 'clicked', slave});
    set(master(NaN, [], 'get', 'hbtnd'), 'callback', {master, 'clicked', slave});
    set(master(NaN, [], 'get', 'hbtni'), 'callback', {master, 'clicked', slave});
    set(hbtn1, 'callback', {slave, 'clicked'});
    set(hbtn2, 'callback', {slave, 'clicked'});
    set(hbtnc, 'callback', {slave, 'clicked', @cleanUpSlave});

    setappdata(hmaster, 'controller', master);
    setappdata(hslave, 'controller', slave);

endfunction;

function hslave = cleanUpSlave()

    master = getappdata(hmaster, 'controller');
    master = master( ...
        master(NaN, [], 'get', 'hparent'), ...
        master(NaN, [], 'get', 'hbtnl'), ...
        master(NaN, [], 'get', 'hbtne'), ...
        master(NaN, [], 'get', 'hbtnd'), ...
        master(NaN, [], 'get', 'hbtni'), ...
        hslave ...
        );

    set(master(NaN, [], 'get', 'hbtnl'), 'enable', 'on'),
    set(master(NaN, [], 'get', 'hbtne'), 'enable', 'off'),
    set(master(NaN, [], 'get', 'hbtnd'), 'enable', 'off'),
    set(master(NaN, [], 'get', 'hbtni'), 'enable', 'off'),

    set(hbtnl, 'callback', {@launchSlave});

    setappdata(hmaster, 'controller', master);

    hslave = NaN;

endfunction;
